import type { NodeTypes } from '@xyflow/react'
import { EdgeNode, StartNode } from '.'

const DEFAULT_COMMAND_NODE_WIDTH = 40
const DEFAULT_COMMAND_NODE_HEIGHT = 40
const DEFAULT_GHOST_NODE_WIDTH = 10
const DEFAULT_GHOST_NODE_HEIGHT = 10
const DEFAULT_MEMO_NODE_WIDTH = 200
const DEFAULT_MEMO_NODE_HEIGHT = 100
const DEFAULT_GROUP_NODE_FOLD_WIDTH = DEFAULT_COMMAND_NODE_WIDTH * 2
const DEFAULT_GROUP_NODE_FOLD_HEIGHT = DEFAULT_COMMAND_NODE_HEIGHT * 2
const DEFAULT_GROUP_NODE_WIDTH = 400
const DEFAULT_GROUP_NODE_HEIGHT = 200
const CHILD_PADDING = 25

export {
  CHILD_PADDING,
  DEFAULT_COMMAND_NODE_HEIGHT,
  DEFAULT_COMMAND_NODE_WIDTH,
  DEFAULT_GHOST_NODE_HEIGHT,
  DEFAULT_GHOST_NODE_WIDTH,
  DEFAULT_GROUP_NODE_FOLD_HEIGHT,
  DEFAULT_GROUP_NODE_FOLD_WIDTH,
  DEFAULT_GROUP_NODE_HEIGHT,
  DEFAULT_GROUP_NODE_WIDTH,
  DEFAULT_MEMO_NODE_HEIGHT,
  DEFAULT_MEMO_NODE_WIDTH,
}

export const nodeTypes: NodeTypes = {
  start: StartNode,
  edge: EdgeNode,
}
