// Code generated by ent, DO NOT EDIT.

package edge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the edge type in the database.
	Label = "edge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceHandle holds the string denoting the source_handle field in the database.
	FieldSourceHandle = "source_handle"
	// FieldTargetHandle holds the string denoting the target_handle field in the database.
	FieldTargetHandle = "target_handle"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeFlow holds the string denoting the flow edge name in mutations.
	EdgeFlow = "flow"
	// EdgeSourceNode holds the string denoting the source_node edge name in mutations.
	EdgeSourceNode = "source_node"
	// EdgeTargetNode holds the string denoting the target_node edge name in mutations.
	EdgeTargetNode = "target_node"
	// Table holds the table name of the edge in the database.
	Table = "edges"
	// FlowTable is the table that holds the flow relation/edge.
	FlowTable = "edges"
	// FlowInverseTable is the table name for the Flow entity.
	// It exists in this package in order to avoid circular dependency with the "flow" package.
	FlowInverseTable = "flows"
	// FlowColumn is the table column denoting the flow relation/edge.
	FlowColumn = "flow_edges"
	// SourceNodeTable is the table that holds the source_node relation/edge.
	SourceNodeTable = "edges"
	// SourceNodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	SourceNodeInverseTable = "nodes"
	// SourceNodeColumn is the table column denoting the source_node relation/edge.
	SourceNodeColumn = "source_node_id"
	// TargetNodeTable is the table that holds the target_node relation/edge.
	TargetNodeTable = "edges"
	// TargetNodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	TargetNodeInverseTable = "nodes"
	// TargetNodeColumn is the table column denoting the target_node relation/edge.
	TargetNodeColumn = "target_node_id"
)

// Columns holds all SQL columns for edge fields.
var Columns = []string{
	FieldID,
	FieldSourceHandle,
	FieldTargetHandle,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "edges"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"flow_edges",
	"source_node_id",
	"target_node_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSourceHandle holds the default value on creation for the "source_handle" field.
	DefaultSourceHandle string
	// DefaultTargetHandle holds the default value on creation for the "target_handle" field.
	DefaultTargetHandle string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Edge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceHandle orders the results by the source_handle field.
func BySourceHandle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceHandle, opts...).ToFunc()
}

// ByTargetHandle orders the results by the target_handle field.
func ByTargetHandle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetHandle, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByFlowField orders the results by flow field.
func ByFlowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlowStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceNodeField orders the results by source_node field.
func BySourceNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceNodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetNodeField orders the results by target_node field.
func ByTargetNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetNodeStep(), sql.OrderByField(field, opts...))
	}
}
func newFlowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FlowTable, FlowColumn),
	)
}
func newSourceNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceNodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceNodeTable, SourceNodeColumn),
	)
}
func newTargetNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetNodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetNodeTable, TargetNodeColumn),
	)
}
