// Code generated by ent, DO NOT EDIT.

package edge

import (
	"sipflow/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldID, id))
}

// SourceHandle applies equality check predicate on the "source_handle" field. It's identical to SourceHandleEQ.
func SourceHandle(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSourceHandle, v))
}

// TargetHandle applies equality check predicate on the "target_handle" field. It's identical to TargetHandleEQ.
func TargetHandle(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTargetHandle, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldCreatedAt, v))
}

// SourceHandleEQ applies the EQ predicate on the "source_handle" field.
func SourceHandleEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSourceHandle, v))
}

// SourceHandleNEQ applies the NEQ predicate on the "source_handle" field.
func SourceHandleNEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldSourceHandle, v))
}

// SourceHandleIn applies the In predicate on the "source_handle" field.
func SourceHandleIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldSourceHandle, vs...))
}

// SourceHandleNotIn applies the NotIn predicate on the "source_handle" field.
func SourceHandleNotIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldSourceHandle, vs...))
}

// SourceHandleGT applies the GT predicate on the "source_handle" field.
func SourceHandleGT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldSourceHandle, v))
}

// SourceHandleGTE applies the GTE predicate on the "source_handle" field.
func SourceHandleGTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldSourceHandle, v))
}

// SourceHandleLT applies the LT predicate on the "source_handle" field.
func SourceHandleLT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldSourceHandle, v))
}

// SourceHandleLTE applies the LTE predicate on the "source_handle" field.
func SourceHandleLTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldSourceHandle, v))
}

// SourceHandleContains applies the Contains predicate on the "source_handle" field.
func SourceHandleContains(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContains(FieldSourceHandle, v))
}

// SourceHandleHasPrefix applies the HasPrefix predicate on the "source_handle" field.
func SourceHandleHasPrefix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasPrefix(FieldSourceHandle, v))
}

// SourceHandleHasSuffix applies the HasSuffix predicate on the "source_handle" field.
func SourceHandleHasSuffix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasSuffix(FieldSourceHandle, v))
}

// SourceHandleIsNil applies the IsNil predicate on the "source_handle" field.
func SourceHandleIsNil() predicate.Edge {
	return predicate.Edge(sql.FieldIsNull(FieldSourceHandle))
}

// SourceHandleNotNil applies the NotNil predicate on the "source_handle" field.
func SourceHandleNotNil() predicate.Edge {
	return predicate.Edge(sql.FieldNotNull(FieldSourceHandle))
}

// SourceHandleEqualFold applies the EqualFold predicate on the "source_handle" field.
func SourceHandleEqualFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEqualFold(FieldSourceHandle, v))
}

// SourceHandleContainsFold applies the ContainsFold predicate on the "source_handle" field.
func SourceHandleContainsFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContainsFold(FieldSourceHandle, v))
}

// TargetHandleEQ applies the EQ predicate on the "target_handle" field.
func TargetHandleEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTargetHandle, v))
}

// TargetHandleNEQ applies the NEQ predicate on the "target_handle" field.
func TargetHandleNEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldTargetHandle, v))
}

// TargetHandleIn applies the In predicate on the "target_handle" field.
func TargetHandleIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldTargetHandle, vs...))
}

// TargetHandleNotIn applies the NotIn predicate on the "target_handle" field.
func TargetHandleNotIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldTargetHandle, vs...))
}

// TargetHandleGT applies the GT predicate on the "target_handle" field.
func TargetHandleGT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldTargetHandle, v))
}

// TargetHandleGTE applies the GTE predicate on the "target_handle" field.
func TargetHandleGTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldTargetHandle, v))
}

// TargetHandleLT applies the LT predicate on the "target_handle" field.
func TargetHandleLT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldTargetHandle, v))
}

// TargetHandleLTE applies the LTE predicate on the "target_handle" field.
func TargetHandleLTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldTargetHandle, v))
}

// TargetHandleContains applies the Contains predicate on the "target_handle" field.
func TargetHandleContains(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContains(FieldTargetHandle, v))
}

// TargetHandleHasPrefix applies the HasPrefix predicate on the "target_handle" field.
func TargetHandleHasPrefix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasPrefix(FieldTargetHandle, v))
}

// TargetHandleHasSuffix applies the HasSuffix predicate on the "target_handle" field.
func TargetHandleHasSuffix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasSuffix(FieldTargetHandle, v))
}

// TargetHandleIsNil applies the IsNil predicate on the "target_handle" field.
func TargetHandleIsNil() predicate.Edge {
	return predicate.Edge(sql.FieldIsNull(FieldTargetHandle))
}

// TargetHandleNotNil applies the NotNil predicate on the "target_handle" field.
func TargetHandleNotNil() predicate.Edge {
	return predicate.Edge(sql.FieldNotNull(FieldTargetHandle))
}

// TargetHandleEqualFold applies the EqualFold predicate on the "target_handle" field.
func TargetHandleEqualFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEqualFold(FieldTargetHandle, v))
}

// TargetHandleContainsFold applies the ContainsFold predicate on the "target_handle" field.
func TargetHandleContainsFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContainsFold(FieldTargetHandle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldCreatedAt, v))
}

// HasFlow applies the HasEdge predicate on the "flow" edge.
func HasFlow() predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FlowTable, FlowColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlowWith applies the HasEdge predicate on the "flow" edge with a given conditions (other predicates).
func HasFlowWith(preds ...predicate.Flow) predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := newFlowStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceNode applies the HasEdge predicate on the "source_node" edge.
func HasSourceNode() predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceNodeTable, SourceNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceNodeWith applies the HasEdge predicate on the "source_node" edge with a given conditions (other predicates).
func HasSourceNodeWith(preds ...predicate.Node) predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := newSourceNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetNode applies the HasEdge predicate on the "target_node" edge.
func HasTargetNode() predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetNodeTable, TargetNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetNodeWith applies the HasEdge predicate on the "target_node" edge with a given conditions (other predicates).
func HasTargetNodeWith(preds ...predicate.Node) predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := newTargetNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.NotPredicates(p))
}
