// Code generated by ent, DO NOT EDIT.

package node

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldXyflowID holds the string denoting the xyflow_id field in the database.
	FieldXyflowID = "xyflow_id"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldPositionX holds the string denoting the position_x field in the database.
	FieldPositionX = "position_x"
	// FieldPositionY holds the string denoting the position_y field in the database.
	FieldPositionY = "position_y"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeFlow holds the string denoting the flow edge name in mutations.
	EdgeFlow = "flow"
	// EdgeOutgoingEdges holds the string denoting the outgoing_edges edge name in mutations.
	EdgeOutgoingEdges = "outgoing_edges"
	// EdgeIncomingEdges holds the string denoting the incoming_edges edge name in mutations.
	EdgeIncomingEdges = "incoming_edges"
	// Table holds the table name of the node in the database.
	Table = "nodes"
	// FlowTable is the table that holds the flow relation/edge.
	FlowTable = "nodes"
	// FlowInverseTable is the table name for the Flow entity.
	// It exists in this package in order to avoid circular dependency with the "flow" package.
	FlowInverseTable = "flows"
	// FlowColumn is the table column denoting the flow relation/edge.
	FlowColumn = "flow_nodes"
	// OutgoingEdgesTable is the table that holds the outgoing_edges relation/edge.
	OutgoingEdgesTable = "edges"
	// OutgoingEdgesInverseTable is the table name for the Edge entity.
	// It exists in this package in order to avoid circular dependency with the "edge" package.
	OutgoingEdgesInverseTable = "edges"
	// OutgoingEdgesColumn is the table column denoting the outgoing_edges relation/edge.
	OutgoingEdgesColumn = "source_node_id"
	// IncomingEdgesTable is the table that holds the incoming_edges relation/edge.
	IncomingEdgesTable = "edges"
	// IncomingEdgesInverseTable is the table name for the Edge entity.
	// It exists in this package in order to avoid circular dependency with the "edge" package.
	IncomingEdgesInverseTable = "edges"
	// IncomingEdgesColumn is the table column denoting the incoming_edges relation/edge.
	IncomingEdgesColumn = "target_node_id"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldXyflowID,
	FieldData,
	FieldPositionX,
	FieldPositionY,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "nodes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"flow_nodes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultXyflowID holds the default value on creation for the "xyflow_id" field.
	DefaultXyflowID string
	// DefaultPositionX holds the default value on creation for the "position_x" field.
	DefaultPositionX float64
	// DefaultPositionY holds the default value on creation for the "position_y" field.
	DefaultPositionY float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByXyflowID orders the results by the xyflow_id field.
func ByXyflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXyflowID, opts...).ToFunc()
}

// ByPositionX orders the results by the position_x field.
func ByPositionX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionX, opts...).ToFunc()
}

// ByPositionY orders the results by the position_y field.
func ByPositionY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionY, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByFlowField orders the results by flow field.
func ByFlowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlowStep(), sql.OrderByField(field, opts...))
	}
}

// ByOutgoingEdgesCount orders the results by outgoing_edges count.
func ByOutgoingEdgesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOutgoingEdgesStep(), opts...)
	}
}

// ByOutgoingEdges orders the results by outgoing_edges terms.
func ByOutgoingEdges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutgoingEdgesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIncomingEdgesCount orders the results by incoming_edges count.
func ByIncomingEdgesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIncomingEdgesStep(), opts...)
	}
}

// ByIncomingEdges orders the results by incoming_edges terms.
func ByIncomingEdges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIncomingEdgesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFlowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FlowTable, FlowColumn),
	)
}
func newOutgoingEdgesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutgoingEdgesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OutgoingEdgesTable, OutgoingEdgesColumn),
	)
}
func newIncomingEdgesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IncomingEdgesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IncomingEdgesTable, IncomingEdgesColumn),
	)
}
