// Code generated by ent, DO NOT EDIT.

package node

import (
	"sipflow/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldType, v))
}

// XyflowID applies equality check predicate on the "xyflow_id" field. It's identical to XyflowIDEQ.
func XyflowID(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldXyflowID, v))
}

// PositionX applies equality check predicate on the "position_x" field. It's identical to PositionXEQ.
func PositionX(v float64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPositionX, v))
}

// PositionY applies equality check predicate on the "position_y" field. It's identical to PositionYEQ.
func PositionY(v float64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPositionY, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldType, v))
}

// XyflowIDEQ applies the EQ predicate on the "xyflow_id" field.
func XyflowIDEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldXyflowID, v))
}

// XyflowIDNEQ applies the NEQ predicate on the "xyflow_id" field.
func XyflowIDNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldXyflowID, v))
}

// XyflowIDIn applies the In predicate on the "xyflow_id" field.
func XyflowIDIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldXyflowID, vs...))
}

// XyflowIDNotIn applies the NotIn predicate on the "xyflow_id" field.
func XyflowIDNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldXyflowID, vs...))
}

// XyflowIDGT applies the GT predicate on the "xyflow_id" field.
func XyflowIDGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldXyflowID, v))
}

// XyflowIDGTE applies the GTE predicate on the "xyflow_id" field.
func XyflowIDGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldXyflowID, v))
}

// XyflowIDLT applies the LT predicate on the "xyflow_id" field.
func XyflowIDLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldXyflowID, v))
}

// XyflowIDLTE applies the LTE predicate on the "xyflow_id" field.
func XyflowIDLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldXyflowID, v))
}

// XyflowIDContains applies the Contains predicate on the "xyflow_id" field.
func XyflowIDContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldXyflowID, v))
}

// XyflowIDHasPrefix applies the HasPrefix predicate on the "xyflow_id" field.
func XyflowIDHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldXyflowID, v))
}

// XyflowIDHasSuffix applies the HasSuffix predicate on the "xyflow_id" field.
func XyflowIDHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldXyflowID, v))
}

// XyflowIDIsNil applies the IsNil predicate on the "xyflow_id" field.
func XyflowIDIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldXyflowID))
}

// XyflowIDNotNil applies the NotNil predicate on the "xyflow_id" field.
func XyflowIDNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldXyflowID))
}

// XyflowIDEqualFold applies the EqualFold predicate on the "xyflow_id" field.
func XyflowIDEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldXyflowID, v))
}

// XyflowIDContainsFold applies the ContainsFold predicate on the "xyflow_id" field.
func XyflowIDContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldXyflowID, v))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldData))
}

// PositionXEQ applies the EQ predicate on the "position_x" field.
func PositionXEQ(v float64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPositionX, v))
}

// PositionXNEQ applies the NEQ predicate on the "position_x" field.
func PositionXNEQ(v float64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldPositionX, v))
}

// PositionXIn applies the In predicate on the "position_x" field.
func PositionXIn(vs ...float64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldPositionX, vs...))
}

// PositionXNotIn applies the NotIn predicate on the "position_x" field.
func PositionXNotIn(vs ...float64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldPositionX, vs...))
}

// PositionXGT applies the GT predicate on the "position_x" field.
func PositionXGT(v float64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldPositionX, v))
}

// PositionXGTE applies the GTE predicate on the "position_x" field.
func PositionXGTE(v float64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldPositionX, v))
}

// PositionXLT applies the LT predicate on the "position_x" field.
func PositionXLT(v float64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldPositionX, v))
}

// PositionXLTE applies the LTE predicate on the "position_x" field.
func PositionXLTE(v float64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldPositionX, v))
}

// PositionYEQ applies the EQ predicate on the "position_y" field.
func PositionYEQ(v float64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPositionY, v))
}

// PositionYNEQ applies the NEQ predicate on the "position_y" field.
func PositionYNEQ(v float64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldPositionY, v))
}

// PositionYIn applies the In predicate on the "position_y" field.
func PositionYIn(vs ...float64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldPositionY, vs...))
}

// PositionYNotIn applies the NotIn predicate on the "position_y" field.
func PositionYNotIn(vs ...float64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldPositionY, vs...))
}

// PositionYGT applies the GT predicate on the "position_y" field.
func PositionYGT(v float64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldPositionY, v))
}

// PositionYGTE applies the GTE predicate on the "position_y" field.
func PositionYGTE(v float64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldPositionY, v))
}

// PositionYLT applies the LT predicate on the "position_y" field.
func PositionYLT(v float64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldPositionY, v))
}

// PositionYLTE applies the LTE predicate on the "position_y" field.
func PositionYLTE(v float64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldPositionY, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCreatedAt, v))
}

// HasFlow applies the HasEdge predicate on the "flow" edge.
func HasFlow() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FlowTable, FlowColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlowWith applies the HasEdge predicate on the "flow" edge with a given conditions (other predicates).
func HasFlowWith(preds ...predicate.Flow) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newFlowStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOutgoingEdges applies the HasEdge predicate on the "outgoing_edges" edge.
func HasOutgoingEdges() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OutgoingEdgesTable, OutgoingEdgesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOutgoingEdgesWith applies the HasEdge predicate on the "outgoing_edges" edge with a given conditions (other predicates).
func HasOutgoingEdgesWith(preds ...predicate.Edge) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newOutgoingEdgesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIncomingEdges applies the HasEdge predicate on the "incoming_edges" edge.
func HasIncomingEdges() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IncomingEdgesTable, IncomingEdgesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIncomingEdgesWith applies the HasEdge predicate on the "incoming_edges" edge with a given conditions (other predicates).
func HasIncomingEdgesWith(preds ...predicate.Edge) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newIncomingEdgesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Node) predicate.Node {
	return predicate.Node(sql.NotPredicates(p))
}
