// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"time"
)

type NodeProperty struct {
	ScenarioID     string
	NodeID         string
	SchemaVersion  int64
	PropertiesJson string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Project struct {
	ID        string
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Scenario struct {
	ID        string
	ProjectID string
	Name      string
	FlowData  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ScenarioEdge struct {
	ScenarioID   string
	EdgeID       string
	SourceNodeID string
	TargetNodeID string
	SourceHandle sql.NullString
	BranchType   string
	DataJson     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ScenarioNode struct {
	ScenarioID    string
	NodeID        string
	NodeType      string
	Label         string
	SipInstanceID sql.NullString
	PositionX     float64
	PositionY     float64
	Width         sql.NullFloat64
	Height        sql.NullFloat64
	ZIndex        int64
	StyleJson     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
