// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenarios (
  id,
  project_id,
  name,
  flow_data,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, '{}', ?, ?
)
RETURNING id, project_id, name, flow_data, created_at, updated_at
`

type CreateScenarioParams struct {
	ID        string
	ProjectID string
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error) {
	row := q.db.QueryRowContext(ctx, createScenario,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.FlowData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNodeProperty = `-- name: DeleteNodeProperty :execrows
DELETE FROM node_properties
WHERE scenario_id = ? AND node_id = ?
`

type DeleteNodePropertyParams struct {
	ScenarioID string
	NodeID     string
}

func (q *Queries) DeleteNodeProperty(ctx context.Context, arg DeleteNodePropertyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNodeProperty, arg.ScenarioID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScenario = `-- name: DeleteScenario :execrows
DELETE FROM scenarios
WHERE id = ?
`

func (q *Queries) DeleteScenario(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScenario, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScenarioEdge = `-- name: DeleteScenarioEdge :execrows
DELETE FROM scenario_edges
WHERE scenario_id = ? AND edge_id = ?
`

type DeleteScenarioEdgeParams struct {
	ScenarioID string
	EdgeID     string
}

func (q *Queries) DeleteScenarioEdge(ctx context.Context, arg DeleteScenarioEdgeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScenarioEdge, arg.ScenarioID, arg.EdgeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScenarioEdgesByScenario = `-- name: DeleteScenarioEdgesByScenario :execrows
DELETE FROM scenario_edges
WHERE scenario_id = ?
`

func (q *Queries) DeleteScenarioEdgesByScenario(ctx context.Context, scenarioID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScenarioEdgesByScenario, scenarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScenarioNode = `-- name: DeleteScenarioNode :execrows
DELETE FROM scenario_nodes
WHERE scenario_id = ? AND node_id = ?
`

type DeleteScenarioNodeParams struct {
	ScenarioID string
	NodeID     string
}

func (q *Queries) DeleteScenarioNode(ctx context.Context, arg DeleteScenarioNodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScenarioNode, arg.ScenarioID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScenarioNodesByScenario = `-- name: DeleteScenarioNodesByScenario :execrows
DELETE FROM scenario_nodes
WHERE scenario_id = ?
`

func (q *Queries) DeleteScenarioNodesByScenario(ctx context.Context, scenarioID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScenarioNodesByScenario, scenarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNodeProperty = `-- name: GetNodeProperty :one
SELECT scenario_id, node_id, schema_version, properties_json, created_at, updated_at
FROM node_properties
WHERE scenario_id = ? AND node_id = ?
LIMIT 1
`

type GetNodePropertyParams struct {
	ScenarioID string
	NodeID     string
}

func (q *Queries) GetNodeProperty(ctx context.Context, arg GetNodePropertyParams) (NodeProperty, error) {
	row := q.db.QueryRowContext(ctx, getNodeProperty, arg.ScenarioID, arg.NodeID)
	var i NodeProperty
	err := row.Scan(
		&i.ScenarioID,
		&i.NodeID,
		&i.SchemaVersion,
		&i.PropertiesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT id, project_id, name, flow_data, created_at, updated_at
FROM scenarios
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetScenario(ctx context.Context, id string) (Scenario, error) {
	row := q.db.QueryRowContext(ctx, getScenario, id)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.FlowData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScenarioEdges = `-- name: ListScenarioEdges :many
SELECT
  scenario_id,
  edge_id,
  source_node_id,
  target_node_id,
  source_handle,
  branch_type,
  data_json,
  created_at,
  updated_at
FROM scenario_edges
WHERE scenario_id = ?
ORDER BY edge_id
`

func (q *Queries) ListScenarioEdges(ctx context.Context, scenarioID string) ([]ScenarioEdge, error) {
	rows, err := q.db.QueryContext(ctx, listScenarioEdges, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScenarioEdge
	for rows.Next() {
		var i ScenarioEdge
		if err := rows.Scan(
			&i.ScenarioID,
			&i.EdgeID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.SourceHandle,
			&i.BranchType,
			&i.DataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarioNodes = `-- name: ListScenarioNodes :many
SELECT
  scenario_id,
  node_id,
  node_type,
  label,
  sip_instance_id,
  position_x,
  position_y,
  width,
  height,
  z_index,
  style_json,
  created_at,
  updated_at
FROM scenario_nodes
WHERE scenario_id = ?
ORDER BY node_id
`

func (q *Queries) ListScenarioNodes(ctx context.Context, scenarioID string) ([]ScenarioNode, error) {
	rows, err := q.db.QueryContext(ctx, listScenarioNodes, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScenarioNode
	for rows.Next() {
		var i ScenarioNode
		if err := rows.Scan(
			&i.ScenarioID,
			&i.NodeID,
			&i.NodeType,
			&i.Label,
			&i.SipInstanceID,
			&i.PositionX,
			&i.PositionY,
			&i.Width,
			&i.Height,
			&i.ZIndex,
			&i.StyleJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarios = `-- name: ListScenarios :many
SELECT id, project_id, name, created_at, updated_at
FROM scenarios
WHERE project_id = ?
ORDER BY updated_at DESC
`

type ListScenariosRow struct {
	ID        string
	ProjectID string
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListScenarios(ctx context.Context, projectID string) ([]ListScenariosRow, error) {
	rows, err := q.db.QueryContext(ctx, listScenarios, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenariosRow
	for rows.Next() {
		var i ListScenariosRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameScenario = `-- name: RenameScenario :execrows
UPDATE scenarios
SET name = ?, updated_at = ?
WHERE id = ?
`

type RenameScenarioParams struct {
	Name      string
	UpdatedAt sql.NullTime
	ID        string
}

func (q *Queries) RenameScenario(ctx context.Context, arg RenameScenarioParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameScenario, arg.Name, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveScenario = `-- name: SaveScenario :execrows
UPDATE scenarios
SET flow_data = ?, updated_at = ?
WHERE id = ?
`

type SaveScenarioParams struct {
	FlowData  string
	UpdatedAt sql.NullTime
	ID        string
}

func (q *Queries) SaveScenario(ctx context.Context, arg SaveScenarioParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveScenario, arg.FlowData, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertNodeProperty = `-- name: UpsertNodeProperty :exec
INSERT INTO node_properties (
  scenario_id,
  node_id,
  schema_version,
  properties_json,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
ON CONFLICT(scenario_id, node_id) DO UPDATE SET
  schema_version = excluded.schema_version,
  properties_json = excluded.properties_json,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertNodePropertyParams struct {
	ScenarioID     string
	NodeID         string
	SchemaVersion  int64
	PropertiesJson string
}

func (q *Queries) UpsertNodeProperty(ctx context.Context, arg UpsertNodePropertyParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeProperty,
		arg.ScenarioID,
		arg.NodeID,
		arg.SchemaVersion,
		arg.PropertiesJson,
	)
	return err
}

const upsertScenarioEdge = `-- name: UpsertScenarioEdge :exec
INSERT INTO scenario_edges (
  scenario_id,
  edge_id,
  source_node_id,
  target_node_id,
  source_handle,
  branch_type,
  data_json,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
ON CONFLICT(scenario_id, edge_id) DO UPDATE SET
  source_node_id = excluded.source_node_id,
  target_node_id = excluded.target_node_id,
  source_handle = excluded.source_handle,
  branch_type = excluded.branch_type,
  data_json = excluded.data_json,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertScenarioEdgeParams struct {
	ScenarioID   string
	EdgeID       string
	SourceNodeID string
	TargetNodeID string
	SourceHandle sql.NullString
	BranchType   string
	DataJson     string
}

func (q *Queries) UpsertScenarioEdge(ctx context.Context, arg UpsertScenarioEdgeParams) error {
	_, err := q.db.ExecContext(ctx, upsertScenarioEdge,
		arg.ScenarioID,
		arg.EdgeID,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.SourceHandle,
		arg.BranchType,
		arg.DataJson,
	)
	return err
}

const upsertScenarioNode = `-- name: UpsertScenarioNode :exec
INSERT INTO scenario_nodes (
  scenario_id,
  node_id,
  node_type,
  label,
  sip_instance_id,
  position_x,
  position_y,
  width,
  height,
  z_index,
  style_json,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
ON CONFLICT(scenario_id, node_id) DO UPDATE SET
  node_type = excluded.node_type,
  label = excluded.label,
  sip_instance_id = excluded.sip_instance_id,
  position_x = excluded.position_x,
  position_y = excluded.position_y,
  width = excluded.width,
  height = excluded.height,
  z_index = excluded.z_index,
  style_json = excluded.style_json,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertScenarioNodeParams struct {
	ScenarioID    string
	NodeID        string
	NodeType      string
	Label         string
	SipInstanceID sql.NullString
	PositionX     float64
	PositionY     float64
	Width         sql.NullFloat64
	Height        sql.NullFloat64
	ZIndex        int64
	StyleJson     string
}

func (q *Queries) UpsertScenarioNode(ctx context.Context, arg UpsertScenarioNodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertScenarioNode,
		arg.ScenarioID,
		arg.NodeID,
		arg.NodeType,
		arg.Label,
		arg.SipInstanceID,
		arg.PositionX,
		arg.PositionY,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.StyleJson,
	)
	return err
}
