// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';
import {ent} from '../models';

export function CreateFlow(arg1:string,arg2:string):Promise<handler.Response_sipflow_ent_Flow_>;

export function DeleteFlow(arg1:number):Promise<handler.Response_bool_>;

export function GetFlow(arg1:number):Promise<handler.Response_sipflow_ent_Flow_>;

export function ListFlows():Promise<handler.Response___sipflow_ent_Flow_>;

export function SetEntClient(arg1:ent.Client):Promise<void>;
