// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFlow(arg1, arg2) {
  return window['go']['handler']['FlowService']['CreateFlow'](arg1, arg2);
}

export function DeleteFlow(arg1) {
  return window['go']['handler']['FlowService']['DeleteFlow'](arg1);
}

export function GetFlow(arg1) {
  return window['go']['handler']['FlowService']['GetFlow'](arg1);
}

export function ListFlows() {
  return window['go']['handler']['FlowService']['ListFlows']();
}

export function SetEntClient(arg1) {
  return window['go']['handler']['FlowService']['SetEntClient'](arg1);
}
