// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';
import {context} from '../models';

export function CloseProject():Promise<handler.Response_bool_>;

export function CurrentProjectPath():Promise<string>;

export function IsProjectOpen():Promise<boolean>;

export function NewProject():Promise<handler.Response_bool_>;

export function OpenProject():Promise<handler.Response_string_>;

export function SaveProjectAs():Promise<handler.Response_string_>;

export function SetContext(arg1:context.Context):Promise<void>;
