// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject() {
  return window['go']['handler']['ProjectService']['CloseProject']();
}

export function CurrentProjectPath() {
  return window['go']['handler']['ProjectService']['CurrentProjectPath']();
}

export function IsProjectOpen() {
  return window['go']['handler']['ProjectService']['IsProjectOpen']();
}

export function NewProject() {
  return window['go']['handler']['ProjectService']['NewProject']();
}

export function OpenProject() {
  return window['go']['handler']['ProjectService']['OpenProject']();
}

export function SaveProjectAs() {
  return window['go']['handler']['ProjectService']['SaveProjectAs']();
}
