// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function Bye(arg1:string):Promise<handler.Response_bool_>;

export function Cancel(arg1:string):Promise<handler.Response_bool_>;

export function CreateServer(arg1:handler.CreateServerRequest):Promise<handler.Response_sipflow_ent_SIPServer_>;

export function DeleteServer(arg1:number):Promise<handler.Response_bool_>;

export function GetServer(arg1:number):Promise<handler.Response_sipflow_ent_SIPServer_>;

export function GetUAStatus(arg1:string):Promise<handler.Response_map_string_interface____>;

export function ListServers():Promise<handler.Response___sipflow_internal_handler_SIPServerMeta_>;

export function ListUAStatuses():Promise<handler.Response___map_string_interface____>;

export function MakeCall(arg1:string,arg2:string):Promise<handler.Response_string_>;

export function SetSIPTrace(arg1:boolean):Promise<handler.Response_bool_>;

export function StartUA(arg1:string,arg2:number):Promise<handler.Response_bool_>;

export function StopAllUAs():Promise<handler.Response_bool_>;

export function StopUA(arg1:string):Promise<handler.Response_bool_>;

export function UpdateServer(arg1:handler.UpdateServerRequest):Promise<handler.Response_sipflow_ent_SIPServer_>;
