// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1) {
  return window['go']['handler']['SIPService']['CreateServer'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['handler']['SIPService']['DeleteServer'](arg1);
}

export function GetServer(arg1) {
  return window['go']['handler']['SIPService']['GetServer'](arg1);
}

export function GetUAStatus(arg1) {
  return window['go']['handler']['SIPService']['GetUAStatus'](arg1);
}

export function ListServers() {
  return window['go']['handler']['SIPService']['ListServers']();
}

export function ListUAStatuses() {
  return window['go']['handler']['SIPService']['ListUAStatuses']();
}

export function SetSIPTrace(arg1) {
  return window['go']['handler']['SIPService']['SetSIPTrace'](arg1);
}

export function StartUA(arg1, arg2) {
  return window['go']['handler']['SIPService']['StartUA'](arg1, arg2);
}

export function StopAllUAs() {
  return window['go']['handler']['SIPService']['StopAllUAs']();
}

export function StopUA(arg1) {
  return window['go']['handler']['SIPService']['StopUA'](arg1);
}

export function UpdateServer(arg1) {
  return window['go']['handler']['SIPService']['UpdateServer'](arg1);
}
