// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EdgesColumns holds the columns for the "edges" table.
	EdgesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "xyflow_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "source_handle", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "target_handle", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "data", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "flow_edges", Type: field.TypeInt},
		{Name: "source_node_id", Type: field.TypeInt},
		{Name: "target_node_id", Type: field.TypeInt},
	}
	// EdgesTable holds the schema information for the "edges" table.
	EdgesTable = &schema.Table{
		Name:       "edges",
		Columns:    EdgesColumns,
		PrimaryKey: []*schema.Column{EdgesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "edges_flows_edges",
				Columns:    []*schema.Column{EdgesColumns[7]},
				RefColumns: []*schema.Column{FlowsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "edges_nodes_outgoing_edges",
				Columns:    []*schema.Column{EdgesColumns[8]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "edges_nodes_incoming_edges",
				Columns:    []*schema.Column{EdgesColumns[9]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FlowsColumns holds the columns for the "flows" table.
	FlowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "viewport_x", Type: field.TypeFloat64, Default: 0},
		{Name: "viewport_y", Type: field.TypeFloat64, Default: 0},
		{Name: "viewport_zoom", Type: field.TypeFloat64, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FlowsTable holds the schema information for the "flows" table.
	FlowsTable = &schema.Table{
		Name:       "flows",
		Columns:    FlowsColumns,
		PrimaryKey: []*schema.Column{FlowsColumns[0]},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "xyflow_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "data", Type: field.TypeJSON, Nullable: true},
		{Name: "position_x", Type: field.TypeFloat64, Default: 0},
		{Name: "position_y", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "flow_nodes", Type: field.TypeInt},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "nodes_flows_nodes",
				Columns:    []*schema.Column{NodesColumns[7]},
				RefColumns: []*schema.Column{FlowsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EdgesTable,
		FlowsTable,
		NodesTable,
	}
)

func init() {
	EdgesTable.ForeignKeys[0].RefTable = FlowsTable
	EdgesTable.ForeignKeys[1].RefTable = NodesTable
	EdgesTable.ForeignKeys[2].RefTable = NodesTable
	NodesTable.ForeignKeys[0].RefTable = FlowsTable
}
