// Code generated by ent, DO NOT EDIT.

package flow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the flow type in the database.
	Label = "flow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldViewportX holds the string denoting the viewport_x field in the database.
	FieldViewportX = "viewport_x"
	// FieldViewportY holds the string denoting the viewport_y field in the database.
	FieldViewportY = "viewport_y"
	// FieldViewportZoom holds the string denoting the viewport_zoom field in the database.
	FieldViewportZoom = "viewport_zoom"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNodes holds the string denoting the nodes edge name in mutations.
	EdgeNodes = "nodes"
	// EdgeEdges holds the string denoting the edges edge name in mutations.
	EdgeEdges = "edges"
	// Table holds the table name of the flow in the database.
	Table = "flows"
	// NodesTable is the table that holds the nodes relation/edge.
	NodesTable = "nodes"
	// NodesInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodesInverseTable = "nodes"
	// NodesColumn is the table column denoting the nodes relation/edge.
	NodesColumn = "flow_nodes"
	// EdgesTable is the table that holds the edges relation/edge.
	EdgesTable = "edges"
	// EdgesInverseTable is the table name for the Edge entity.
	// It exists in this package in order to avoid circular dependency with the "edge" package.
	EdgesInverseTable = "edges"
	// EdgesColumn is the table column denoting the edges relation/edge.
	EdgesColumn = "flow_edges"
)

// Columns holds all SQL columns for flow fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldViewportX,
	FieldViewportY,
	FieldViewportZoom,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultViewportX holds the default value on creation for the "viewport_x" field.
	DefaultViewportX float64
	// DefaultViewportY holds the default value on creation for the "viewport_y" field.
	DefaultViewportY float64
	// DefaultViewportZoom holds the default value on creation for the "viewport_zoom" field.
	DefaultViewportZoom float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Flow queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByViewportX orders the results by the viewport_x field.
func ByViewportX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewportX, opts...).ToFunc()
}

// ByViewportY orders the results by the viewport_y field.
func ByViewportY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewportY, opts...).ToFunc()
}

// ByViewportZoom orders the results by the viewport_zoom field.
func ByViewportZoom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewportZoom, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNodesCount orders the results by nodes count.
func ByNodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNodesStep(), opts...)
	}
}

// ByNodes orders the results by nodes terms.
func ByNodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEdgesCount orders the results by edges count.
func ByEdgesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEdgesStep(), opts...)
	}
}

// ByEdges orders the results by edges terms.
func ByEdges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEdgesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NodesTable, NodesColumn),
	)
}
func newEdgesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EdgesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EdgesTable, EdgesColumn),
	)
}
