// Code generated by ent, DO NOT EDIT.

package flow

import (
	"sipflow/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldDescription, v))
}

// ViewportX applies equality check predicate on the "viewport_x" field. It's identical to ViewportXEQ.
func ViewportX(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldViewportX, v))
}

// ViewportY applies equality check predicate on the "viewport_y" field. It's identical to ViewportYEQ.
func ViewportY(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldViewportY, v))
}

// ViewportZoom applies equality check predicate on the "viewport_zoom" field. It's identical to ViewportZoomEQ.
func ViewportZoom(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldViewportZoom, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Flow {
	return predicate.Flow(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Flow {
	return predicate.Flow(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContainsFold(FieldDescription, v))
}

// ViewportXEQ applies the EQ predicate on the "viewport_x" field.
func ViewportXEQ(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldViewportX, v))
}

// ViewportXNEQ applies the NEQ predicate on the "viewport_x" field.
func ViewportXNEQ(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldViewportX, v))
}

// ViewportXIn applies the In predicate on the "viewport_x" field.
func ViewportXIn(vs ...float64) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldViewportX, vs...))
}

// ViewportXNotIn applies the NotIn predicate on the "viewport_x" field.
func ViewportXNotIn(vs ...float64) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldViewportX, vs...))
}

// ViewportXGT applies the GT predicate on the "viewport_x" field.
func ViewportXGT(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldViewportX, v))
}

// ViewportXGTE applies the GTE predicate on the "viewport_x" field.
func ViewportXGTE(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldViewportX, v))
}

// ViewportXLT applies the LT predicate on the "viewport_x" field.
func ViewportXLT(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldViewportX, v))
}

// ViewportXLTE applies the LTE predicate on the "viewport_x" field.
func ViewportXLTE(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldViewportX, v))
}

// ViewportYEQ applies the EQ predicate on the "viewport_y" field.
func ViewportYEQ(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldViewportY, v))
}

// ViewportYNEQ applies the NEQ predicate on the "viewport_y" field.
func ViewportYNEQ(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldViewportY, v))
}

// ViewportYIn applies the In predicate on the "viewport_y" field.
func ViewportYIn(vs ...float64) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldViewportY, vs...))
}

// ViewportYNotIn applies the NotIn predicate on the "viewport_y" field.
func ViewportYNotIn(vs ...float64) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldViewportY, vs...))
}

// ViewportYGT applies the GT predicate on the "viewport_y" field.
func ViewportYGT(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldViewportY, v))
}

// ViewportYGTE applies the GTE predicate on the "viewport_y" field.
func ViewportYGTE(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldViewportY, v))
}

// ViewportYLT applies the LT predicate on the "viewport_y" field.
func ViewportYLT(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldViewportY, v))
}

// ViewportYLTE applies the LTE predicate on the "viewport_y" field.
func ViewportYLTE(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldViewportY, v))
}

// ViewportZoomEQ applies the EQ predicate on the "viewport_zoom" field.
func ViewportZoomEQ(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldViewportZoom, v))
}

// ViewportZoomNEQ applies the NEQ predicate on the "viewport_zoom" field.
func ViewportZoomNEQ(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldViewportZoom, v))
}

// ViewportZoomIn applies the In predicate on the "viewport_zoom" field.
func ViewportZoomIn(vs ...float64) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldViewportZoom, vs...))
}

// ViewportZoomNotIn applies the NotIn predicate on the "viewport_zoom" field.
func ViewportZoomNotIn(vs ...float64) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldViewportZoom, vs...))
}

// ViewportZoomGT applies the GT predicate on the "viewport_zoom" field.
func ViewportZoomGT(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldViewportZoom, v))
}

// ViewportZoomGTE applies the GTE predicate on the "viewport_zoom" field.
func ViewportZoomGTE(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldViewportZoom, v))
}

// ViewportZoomLT applies the LT predicate on the "viewport_zoom" field.
func ViewportZoomLT(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldViewportZoom, v))
}

// ViewportZoomLTE applies the LTE predicate on the "viewport_zoom" field.
func ViewportZoomLTE(v float64) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldViewportZoom, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasNodes applies the HasEdge predicate on the "nodes" edge.
func HasNodes() predicate.Flow {
	return predicate.Flow(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodesTable, NodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodesWith applies the HasEdge predicate on the "nodes" edge with a given conditions (other predicates).
func HasNodesWith(preds ...predicate.Node) predicate.Flow {
	return predicate.Flow(func(s *sql.Selector) {
		step := newNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEdges applies the HasEdge predicate on the "edges" edge.
func HasEdges() predicate.Flow {
	return predicate.Flow(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EdgesTable, EdgesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEdgesWith applies the HasEdge predicate on the "edges" edge with a given conditions (other predicates).
func HasEdgesWith(preds ...predicate.Edge) predicate.Flow {
	return predicate.Flow(func(s *sql.Selector) {
		step := newEdgesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Flow) predicate.Flow {
	return predicate.Flow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Flow) predicate.Flow {
	return predicate.Flow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Flow) predicate.Flow {
	return predicate.Flow(sql.NotPredicates(p))
}
