// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EdgeCreate is the builder for creating a Edge entity.
type EdgeCreate struct {
	config
	mutation *EdgeMutation
	hooks    []Hook
}

// SetSourceHandle sets the "source_handle" field.
func (_c *EdgeCreate) SetSourceHandle(v string) *EdgeCreate {
	_c.mutation.SetSourceHandle(v)
	return _c
}

// SetNillableSourceHandle sets the "source_handle" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableSourceHandle(v *string) *EdgeCreate {
	if v != nil {
		_c.SetSourceHandle(*v)
	}
	return _c
}

// SetTargetHandle sets the "target_handle" field.
func (_c *EdgeCreate) SetTargetHandle(v string) *EdgeCreate {
	_c.mutation.SetTargetHandle(v)
	return _c
}

// SetNillableTargetHandle sets the "target_handle" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableTargetHandle(v *string) *EdgeCreate {
	if v != nil {
		_c.SetTargetHandle(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EdgeCreate) SetCreatedAt(v time.Time) *EdgeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableCreatedAt(v *time.Time) *EdgeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetFlowID sets the "flow" edge to the Flow entity by ID.
func (_c *EdgeCreate) SetFlowID(id int) *EdgeCreate {
	_c.mutation.SetFlowID(id)
	return _c
}

// SetFlow sets the "flow" edge to the Flow entity.
func (_c *EdgeCreate) SetFlow(v *Flow) *EdgeCreate {
	return _c.SetFlowID(v.ID)
}

// SetSourceNodeID sets the "source_node" edge to the Node entity by ID.
func (_c *EdgeCreate) SetSourceNodeID(id int) *EdgeCreate {
	_c.mutation.SetSourceNodeID(id)
	return _c
}

// SetSourceNode sets the "source_node" edge to the Node entity.
func (_c *EdgeCreate) SetSourceNode(v *Node) *EdgeCreate {
	return _c.SetSourceNodeID(v.ID)
}

// SetTargetNodeID sets the "target_node" edge to the Node entity by ID.
func (_c *EdgeCreate) SetTargetNodeID(id int) *EdgeCreate {
	_c.mutation.SetTargetNodeID(id)
	return _c
}

// SetTargetNode sets the "target_node" edge to the Node entity.
func (_c *EdgeCreate) SetTargetNode(v *Node) *EdgeCreate {
	return _c.SetTargetNodeID(v.ID)
}

// Mutation returns the EdgeMutation object of the builder.
func (_c *EdgeCreate) Mutation() *EdgeMutation {
	return _c.mutation
}

// Save creates the Edge in the database.
func (_c *EdgeCreate) Save(ctx context.Context) (*Edge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EdgeCreate) SaveX(ctx context.Context) *Edge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EdgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EdgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EdgeCreate) defaults() {
	if _, ok := _c.mutation.SourceHandle(); !ok {
		v := edge.DefaultSourceHandle
		_c.mutation.SetSourceHandle(v)
	}
	if _, ok := _c.mutation.TargetHandle(); !ok {
		v := edge.DefaultTargetHandle
		_c.mutation.SetTargetHandle(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := edge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EdgeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Edge.created_at"`)}
	}
	if len(_c.mutation.FlowIDs()) == 0 {
		return &ValidationError{Name: "flow", err: errors.New(`ent: missing required edge "Edge.flow"`)}
	}
	if len(_c.mutation.SourceNodeIDs()) == 0 {
		return &ValidationError{Name: "source_node", err: errors.New(`ent: missing required edge "Edge.source_node"`)}
	}
	if len(_c.mutation.TargetNodeIDs()) == 0 {
		return &ValidationError{Name: "target_node", err: errors.New(`ent: missing required edge "Edge.target_node"`)}
	}
	return nil
}

func (_c *EdgeCreate) sqlSave(ctx context.Context) (*Edge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EdgeCreate) createSpec() (*Edge, *sqlgraph.CreateSpec) {
	var (
		_node = &Edge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(edge.Table, sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SourceHandle(); ok {
		_spec.SetField(edge.FieldSourceHandle, field.TypeString, value)
		_node.SourceHandle = value
	}
	if value, ok := _c.mutation.TargetHandle(); ok {
		_spec.SetField(edge.FieldTargetHandle, field.TypeString, value)
		_node.TargetHandle = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(edge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.FlowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.FlowTable,
			Columns: []string{edge.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.flow_edges = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceNodeTable,
			Columns: []string{edge.SourceNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.source_node_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetNodeTable,
			Columns: []string{edge.TargetNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.target_node_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EdgeCreateBulk is the builder for creating many Edge entities in bulk.
type EdgeCreateBulk struct {
	config
	err      error
	builders []*EdgeCreate
}

// Save creates the Edge entities in the database.
func (_c *EdgeCreateBulk) Save(ctx context.Context) ([]*Edge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Edge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EdgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EdgeCreateBulk) SaveX(ctx context.Context) []*Edge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EdgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EdgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
