// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Edge is the model entity for the Edge schema.
type Edge struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceHandle holds the value of the "source_handle" field.
	SourceHandle string `json:"source_handle,omitempty"`
	// TargetHandle holds the value of the "target_handle" field.
	TargetHandle string `json:"target_handle,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EdgeQuery when eager-loading is set.
	Edges          EdgeEdges `json:"edges"`
	flow_edges     *int
	source_node_id *int
	target_node_id *int
	selectValues   sql.SelectValues
}

// EdgeEdges holds the relations/edges for other nodes in the graph.
type EdgeEdges struct {
	// Flow holds the value of the flow edge.
	Flow *Flow `json:"flow,omitempty"`
	// SourceNode holds the value of the source_node edge.
	SourceNode *Node `json:"source_node,omitempty"`
	// TargetNode holds the value of the target_node edge.
	TargetNode *Node `json:"target_node,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// FlowOrErr returns the Flow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EdgeEdges) FlowOrErr() (*Flow, error) {
	if e.Flow != nil {
		return e.Flow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: flow.Label}
	}
	return nil, &NotLoadedError{edge: "flow"}
}

// SourceNodeOrErr returns the SourceNode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EdgeEdges) SourceNodeOrErr() (*Node, error) {
	if e.SourceNode != nil {
		return e.SourceNode, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "source_node"}
}

// TargetNodeOrErr returns the TargetNode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EdgeEdges) TargetNodeOrErr() (*Node, error) {
	if e.TargetNode != nil {
		return e.TargetNode, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "target_node"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Edge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case edge.FieldID:
			values[i] = new(sql.NullInt64)
		case edge.FieldSourceHandle, edge.FieldTargetHandle:
			values[i] = new(sql.NullString)
		case edge.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case edge.ForeignKeys[0]: // flow_edges
			values[i] = new(sql.NullInt64)
		case edge.ForeignKeys[1]: // source_node_id
			values[i] = new(sql.NullInt64)
		case edge.ForeignKeys[2]: // target_node_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Edge fields.
func (_m *Edge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case edge.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case edge.FieldSourceHandle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_handle", values[i])
			} else if value.Valid {
				_m.SourceHandle = value.String
			}
		case edge.FieldTargetHandle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_handle", values[i])
			} else if value.Valid {
				_m.TargetHandle = value.String
			}
		case edge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case edge.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field flow_edges", value)
			} else if value.Valid {
				_m.flow_edges = new(int)
				*_m.flow_edges = int(value.Int64)
			}
		case edge.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field source_node_id", value)
			} else if value.Valid {
				_m.source_node_id = new(int)
				*_m.source_node_id = int(value.Int64)
			}
		case edge.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field target_node_id", value)
			} else if value.Valid {
				_m.target_node_id = new(int)
				*_m.target_node_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Edge.
// This includes values selected through modifiers, order, etc.
func (_m *Edge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFlow queries the "flow" edge of the Edge entity.
func (_m *Edge) QueryFlow() *FlowQuery {
	return NewEdgeClient(_m.config).QueryFlow(_m)
}

// QuerySourceNode queries the "source_node" edge of the Edge entity.
func (_m *Edge) QuerySourceNode() *NodeQuery {
	return NewEdgeClient(_m.config).QuerySourceNode(_m)
}

// QueryTargetNode queries the "target_node" edge of the Edge entity.
func (_m *Edge) QueryTargetNode() *NodeQuery {
	return NewEdgeClient(_m.config).QueryTargetNode(_m)
}

// Update returns a builder for updating this Edge.
// Note that you need to call Edge.Unwrap() before calling this method if this Edge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Edge) Update() *EdgeUpdateOne {
	return NewEdgeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Edge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Edge) Unwrap() *Edge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Edge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Edge) String() string {
	var builder strings.Builder
	builder.WriteString("Edge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_handle=")
	builder.WriteString(_m.SourceHandle)
	builder.WriteString(", ")
	builder.WriteString("target_handle=")
	builder.WriteString(_m.TargetHandle)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Edges is a parsable slice of Edge.
type Edges []*Edge
