// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"sipflow/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EdgeUpdate is the builder for updating Edge entities.
type EdgeUpdate struct {
	config
	hooks    []Hook
	mutation *EdgeMutation
}

// Where appends a list predicates to the EdgeUpdate builder.
func (_u *EdgeUpdate) Where(ps ...predicate.Edge) *EdgeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceHandle sets the "source_handle" field.
func (_u *EdgeUpdate) SetSourceHandle(v string) *EdgeUpdate {
	_u.mutation.SetSourceHandle(v)
	return _u
}

// SetNillableSourceHandle sets the "source_handle" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableSourceHandle(v *string) *EdgeUpdate {
	if v != nil {
		_u.SetSourceHandle(*v)
	}
	return _u
}

// ClearSourceHandle clears the value of the "source_handle" field.
func (_u *EdgeUpdate) ClearSourceHandle() *EdgeUpdate {
	_u.mutation.ClearSourceHandle()
	return _u
}

// SetTargetHandle sets the "target_handle" field.
func (_u *EdgeUpdate) SetTargetHandle(v string) *EdgeUpdate {
	_u.mutation.SetTargetHandle(v)
	return _u
}

// SetNillableTargetHandle sets the "target_handle" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableTargetHandle(v *string) *EdgeUpdate {
	if v != nil {
		_u.SetTargetHandle(*v)
	}
	return _u
}

// ClearTargetHandle clears the value of the "target_handle" field.
func (_u *EdgeUpdate) ClearTargetHandle() *EdgeUpdate {
	_u.mutation.ClearTargetHandle()
	return _u
}

// SetFlowID sets the "flow" edge to the Flow entity by ID.
func (_u *EdgeUpdate) SetFlowID(id int) *EdgeUpdate {
	_u.mutation.SetFlowID(id)
	return _u
}

// SetFlow sets the "flow" edge to the Flow entity.
func (_u *EdgeUpdate) SetFlow(v *Flow) *EdgeUpdate {
	return _u.SetFlowID(v.ID)
}

// SetSourceNodeID sets the "source_node" edge to the Node entity by ID.
func (_u *EdgeUpdate) SetSourceNodeID(id int) *EdgeUpdate {
	_u.mutation.SetSourceNodeID(id)
	return _u
}

// SetSourceNode sets the "source_node" edge to the Node entity.
func (_u *EdgeUpdate) SetSourceNode(v *Node) *EdgeUpdate {
	return _u.SetSourceNodeID(v.ID)
}

// SetTargetNodeID sets the "target_node" edge to the Node entity by ID.
func (_u *EdgeUpdate) SetTargetNodeID(id int) *EdgeUpdate {
	_u.mutation.SetTargetNodeID(id)
	return _u
}

// SetTargetNode sets the "target_node" edge to the Node entity.
func (_u *EdgeUpdate) SetTargetNode(v *Node) *EdgeUpdate {
	return _u.SetTargetNodeID(v.ID)
}

// Mutation returns the EdgeMutation object of the builder.
func (_u *EdgeUpdate) Mutation() *EdgeMutation {
	return _u.mutation
}

// ClearFlow clears the "flow" edge to the Flow entity.
func (_u *EdgeUpdate) ClearFlow() *EdgeUpdate {
	_u.mutation.ClearFlow()
	return _u
}

// ClearSourceNode clears the "source_node" edge to the Node entity.
func (_u *EdgeUpdate) ClearSourceNode() *EdgeUpdate {
	_u.mutation.ClearSourceNode()
	return _u
}

// ClearTargetNode clears the "target_node" edge to the Node entity.
func (_u *EdgeUpdate) ClearTargetNode() *EdgeUpdate {
	_u.mutation.ClearTargetNode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EdgeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EdgeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EdgeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EdgeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EdgeUpdate) check() error {
	if _u.mutation.FlowCleared() && len(_u.mutation.FlowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.flow"`)
	}
	if _u.mutation.SourceNodeCleared() && len(_u.mutation.SourceNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.source_node"`)
	}
	if _u.mutation.TargetNodeCleared() && len(_u.mutation.TargetNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.target_node"`)
	}
	return nil
}

func (_u *EdgeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(edge.Table, edge.Columns, sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceHandle(); ok {
		_spec.SetField(edge.FieldSourceHandle, field.TypeString, value)
	}
	if _u.mutation.SourceHandleCleared() {
		_spec.ClearField(edge.FieldSourceHandle, field.TypeString)
	}
	if value, ok := _u.mutation.TargetHandle(); ok {
		_spec.SetField(edge.FieldTargetHandle, field.TypeString, value)
	}
	if _u.mutation.TargetHandleCleared() {
		_spec.ClearField(edge.FieldTargetHandle, field.TypeString)
	}
	if _u.mutation.FlowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.FlowTable,
			Columns: []string{edge.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.FlowTable,
			Columns: []string{edge.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceNodeTable,
			Columns: []string{edge.SourceNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceNodeTable,
			Columns: []string{edge.SourceNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetNodeTable,
			Columns: []string{edge.TargetNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetNodeTable,
			Columns: []string{edge.TargetNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{edge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EdgeUpdateOne is the builder for updating a single Edge entity.
type EdgeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EdgeMutation
}

// SetSourceHandle sets the "source_handle" field.
func (_u *EdgeUpdateOne) SetSourceHandle(v string) *EdgeUpdateOne {
	_u.mutation.SetSourceHandle(v)
	return _u
}

// SetNillableSourceHandle sets the "source_handle" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableSourceHandle(v *string) *EdgeUpdateOne {
	if v != nil {
		_u.SetSourceHandle(*v)
	}
	return _u
}

// ClearSourceHandle clears the value of the "source_handle" field.
func (_u *EdgeUpdateOne) ClearSourceHandle() *EdgeUpdateOne {
	_u.mutation.ClearSourceHandle()
	return _u
}

// SetTargetHandle sets the "target_handle" field.
func (_u *EdgeUpdateOne) SetTargetHandle(v string) *EdgeUpdateOne {
	_u.mutation.SetTargetHandle(v)
	return _u
}

// SetNillableTargetHandle sets the "target_handle" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableTargetHandle(v *string) *EdgeUpdateOne {
	if v != nil {
		_u.SetTargetHandle(*v)
	}
	return _u
}

// ClearTargetHandle clears the value of the "target_handle" field.
func (_u *EdgeUpdateOne) ClearTargetHandle() *EdgeUpdateOne {
	_u.mutation.ClearTargetHandle()
	return _u
}

// SetFlowID sets the "flow" edge to the Flow entity by ID.
func (_u *EdgeUpdateOne) SetFlowID(id int) *EdgeUpdateOne {
	_u.mutation.SetFlowID(id)
	return _u
}

// SetFlow sets the "flow" edge to the Flow entity.
func (_u *EdgeUpdateOne) SetFlow(v *Flow) *EdgeUpdateOne {
	return _u.SetFlowID(v.ID)
}

// SetSourceNodeID sets the "source_node" edge to the Node entity by ID.
func (_u *EdgeUpdateOne) SetSourceNodeID(id int) *EdgeUpdateOne {
	_u.mutation.SetSourceNodeID(id)
	return _u
}

// SetSourceNode sets the "source_node" edge to the Node entity.
func (_u *EdgeUpdateOne) SetSourceNode(v *Node) *EdgeUpdateOne {
	return _u.SetSourceNodeID(v.ID)
}

// SetTargetNodeID sets the "target_node" edge to the Node entity by ID.
func (_u *EdgeUpdateOne) SetTargetNodeID(id int) *EdgeUpdateOne {
	_u.mutation.SetTargetNodeID(id)
	return _u
}

// SetTargetNode sets the "target_node" edge to the Node entity.
func (_u *EdgeUpdateOne) SetTargetNode(v *Node) *EdgeUpdateOne {
	return _u.SetTargetNodeID(v.ID)
}

// Mutation returns the EdgeMutation object of the builder.
func (_u *EdgeUpdateOne) Mutation() *EdgeMutation {
	return _u.mutation
}

// ClearFlow clears the "flow" edge to the Flow entity.
func (_u *EdgeUpdateOne) ClearFlow() *EdgeUpdateOne {
	_u.mutation.ClearFlow()
	return _u
}

// ClearSourceNode clears the "source_node" edge to the Node entity.
func (_u *EdgeUpdateOne) ClearSourceNode() *EdgeUpdateOne {
	_u.mutation.ClearSourceNode()
	return _u
}

// ClearTargetNode clears the "target_node" edge to the Node entity.
func (_u *EdgeUpdateOne) ClearTargetNode() *EdgeUpdateOne {
	_u.mutation.ClearTargetNode()
	return _u
}

// Where appends a list predicates to the EdgeUpdate builder.
func (_u *EdgeUpdateOne) Where(ps ...predicate.Edge) *EdgeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EdgeUpdateOne) Select(field string, fields ...string) *EdgeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Edge entity.
func (_u *EdgeUpdateOne) Save(ctx context.Context) (*Edge, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EdgeUpdateOne) SaveX(ctx context.Context) *Edge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EdgeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EdgeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EdgeUpdateOne) check() error {
	if _u.mutation.FlowCleared() && len(_u.mutation.FlowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.flow"`)
	}
	if _u.mutation.SourceNodeCleared() && len(_u.mutation.SourceNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.source_node"`)
	}
	if _u.mutation.TargetNodeCleared() && len(_u.mutation.TargetNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.target_node"`)
	}
	return nil
}

func (_u *EdgeUpdateOne) sqlSave(ctx context.Context) (_node *Edge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(edge.Table, edge.Columns, sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Edge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, edge.FieldID)
		for _, f := range fields {
			if !edge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != edge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceHandle(); ok {
		_spec.SetField(edge.FieldSourceHandle, field.TypeString, value)
	}
	if _u.mutation.SourceHandleCleared() {
		_spec.ClearField(edge.FieldSourceHandle, field.TypeString)
	}
	if value, ok := _u.mutation.TargetHandle(); ok {
		_spec.SetField(edge.FieldTargetHandle, field.TypeString, value)
	}
	if _u.mutation.TargetHandleCleared() {
		_spec.ClearField(edge.FieldTargetHandle, field.TypeString)
	}
	if _u.mutation.FlowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.FlowTable,
			Columns: []string{edge.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.FlowTable,
			Columns: []string{edge.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceNodeTable,
			Columns: []string{edge.SourceNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceNodeTable,
			Columns: []string{edge.SourceNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetNodeTable,
			Columns: []string{edge.TargetNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetNodeTable,
			Columns: []string{edge.TargetNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Edge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{edge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
