// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sipflow/ent/flow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Flow is the model entity for the Flow schema.
type Flow struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlowQuery when eager-loading is set.
	Edges        FlowEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FlowEdges holds the relations/edges for other nodes in the graph.
type FlowEdges struct {
	// Nodes holds the value of the nodes edge.
	Nodes []*Node `json:"nodes,omitempty"`
	// Edges holds the value of the edges edge.
	Edges []*Edge `json:"edges,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// NodesOrErr returns the Nodes value or an error if the edge
// was not loaded in eager-loading.
func (e FlowEdges) NodesOrErr() ([]*Node, error) {
	if e.loadedTypes[0] {
		return e.Nodes, nil
	}
	return nil, &NotLoadedError{edge: "nodes"}
}

// EdgesOrErr returns the Edges value or an error if the edge
// was not loaded in eager-loading.
func (e FlowEdges) EdgesOrErr() ([]*Edge, error) {
	if e.loadedTypes[1] {
		return e.Edges, nil
	}
	return nil, &NotLoadedError{edge: "edges"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Flow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flow.FieldID:
			values[i] = new(sql.NullInt64)
		case flow.FieldName, flow.FieldDescription:
			values[i] = new(sql.NullString)
		case flow.FieldCreatedAt, flow.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Flow fields.
func (_m *Flow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case flow.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case flow.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case flow.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case flow.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Flow.
// This includes values selected through modifiers, order, etc.
func (_m *Flow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNodes queries the "nodes" edge of the Flow entity.
func (_m *Flow) QueryNodes() *NodeQuery {
	return NewFlowClient(_m.config).QueryNodes(_m)
}

// QueryEdges queries the "edges" edge of the Flow entity.
func (_m *Flow) QueryEdges() *EdgeQuery {
	return NewFlowClient(_m.config).QueryEdges(_m)
}

// Update returns a builder for updating this Flow.
// Note that you need to call Flow.Unwrap() before calling this method if this Flow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Flow) Update() *FlowUpdateOne {
	return NewFlowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Flow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Flow) Unwrap() *Flow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Flow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Flow) String() string {
	var builder strings.Builder
	builder.WriteString("Flow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Flows is a parsable slice of Flow.
type Flows []*Flow
