// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"sipflow/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEdge = "Edge"
	TypeFlow = "Flow"
	TypeNode = "Node"
)

// EdgeMutation represents an operation that mutates the Edge nodes in the graph.
type EdgeMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	source_handle      *string
	target_handle      *string
	created_at         *time.Time
	clearedFields      map[string]struct{}
	flow               *int
	clearedflow        bool
	source_node        *int
	clearedsource_node bool
	target_node        *int
	clearedtarget_node bool
	done               bool
	oldValue           func(context.Context) (*Edge, error)
	predicates         []predicate.Edge
}

var _ ent.Mutation = (*EdgeMutation)(nil)

// edgeOption allows management of the mutation configuration using functional options.
type edgeOption func(*EdgeMutation)

// newEdgeMutation creates new mutation for the Edge entity.
func newEdgeMutation(c config, op Op, opts ...edgeOption) *EdgeMutation {
	m := &EdgeMutation{
		config:        c,
		op:            op,
		typ:           TypeEdge,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEdgeID sets the ID field of the mutation.
func withEdgeID(id int) edgeOption {
	return func(m *EdgeMutation) {
		var (
			err   error
			once  sync.Once
			value *Edge
		)
		m.oldValue = func(ctx context.Context) (*Edge, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Edge.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEdge sets the old Edge of the mutation.
func withEdge(node *Edge) edgeOption {
	return func(m *EdgeMutation) {
		m.oldValue = func(context.Context) (*Edge, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EdgeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EdgeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EdgeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EdgeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Edge.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSourceHandle sets the "source_handle" field.
func (m *EdgeMutation) SetSourceHandle(s string) {
	m.source_handle = &s
}

// SourceHandle returns the value of the "source_handle" field in the mutation.
func (m *EdgeMutation) SourceHandle() (r string, exists bool) {
	v := m.source_handle
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceHandle returns the old "source_handle" field's value of the Edge entity.
// If the Edge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EdgeMutation) OldSourceHandle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceHandle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceHandle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceHandle: %w", err)
	}
	return oldValue.SourceHandle, nil
}

// ClearSourceHandle clears the value of the "source_handle" field.
func (m *EdgeMutation) ClearSourceHandle() {
	m.source_handle = nil
	m.clearedFields[edge.FieldSourceHandle] = struct{}{}
}

// SourceHandleCleared returns if the "source_handle" field was cleared in this mutation.
func (m *EdgeMutation) SourceHandleCleared() bool {
	_, ok := m.clearedFields[edge.FieldSourceHandle]
	return ok
}

// ResetSourceHandle resets all changes to the "source_handle" field.
func (m *EdgeMutation) ResetSourceHandle() {
	m.source_handle = nil
	delete(m.clearedFields, edge.FieldSourceHandle)
}

// SetTargetHandle sets the "target_handle" field.
func (m *EdgeMutation) SetTargetHandle(s string) {
	m.target_handle = &s
}

// TargetHandle returns the value of the "target_handle" field in the mutation.
func (m *EdgeMutation) TargetHandle() (r string, exists bool) {
	v := m.target_handle
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetHandle returns the old "target_handle" field's value of the Edge entity.
// If the Edge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EdgeMutation) OldTargetHandle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetHandle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetHandle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetHandle: %w", err)
	}
	return oldValue.TargetHandle, nil
}

// ClearTargetHandle clears the value of the "target_handle" field.
func (m *EdgeMutation) ClearTargetHandle() {
	m.target_handle = nil
	m.clearedFields[edge.FieldTargetHandle] = struct{}{}
}

// TargetHandleCleared returns if the "target_handle" field was cleared in this mutation.
func (m *EdgeMutation) TargetHandleCleared() bool {
	_, ok := m.clearedFields[edge.FieldTargetHandle]
	return ok
}

// ResetTargetHandle resets all changes to the "target_handle" field.
func (m *EdgeMutation) ResetTargetHandle() {
	m.target_handle = nil
	delete(m.clearedFields, edge.FieldTargetHandle)
}

// SetCreatedAt sets the "created_at" field.
func (m *EdgeMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *EdgeMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Edge entity.
// If the Edge object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EdgeMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *EdgeMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetFlowID sets the "flow" edge to the Flow entity by id.
func (m *EdgeMutation) SetFlowID(id int) {
	m.flow = &id
}

// ClearFlow clears the "flow" edge to the Flow entity.
func (m *EdgeMutation) ClearFlow() {
	m.clearedflow = true
}

// FlowCleared reports if the "flow" edge to the Flow entity was cleared.
func (m *EdgeMutation) FlowCleared() bool {
	return m.clearedflow
}

// FlowID returns the "flow" edge ID in the mutation.
func (m *EdgeMutation) FlowID() (id int, exists bool) {
	if m.flow != nil {
		return *m.flow, true
	}
	return
}

// FlowIDs returns the "flow" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// FlowID instead. It exists only for internal usage by the builders.
func (m *EdgeMutation) FlowIDs() (ids []int) {
	if id := m.flow; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFlow resets all changes to the "flow" edge.
func (m *EdgeMutation) ResetFlow() {
	m.flow = nil
	m.clearedflow = false
}

// SetSourceNodeID sets the "source_node" edge to the Node entity by id.
func (m *EdgeMutation) SetSourceNodeID(id int) {
	m.source_node = &id
}

// ClearSourceNode clears the "source_node" edge to the Node entity.
func (m *EdgeMutation) ClearSourceNode() {
	m.clearedsource_node = true
}

// SourceNodeCleared reports if the "source_node" edge to the Node entity was cleared.
func (m *EdgeMutation) SourceNodeCleared() bool {
	return m.clearedsource_node
}

// SourceNodeID returns the "source_node" edge ID in the mutation.
func (m *EdgeMutation) SourceNodeID() (id int, exists bool) {
	if m.source_node != nil {
		return *m.source_node, true
	}
	return
}

// SourceNodeIDs returns the "source_node" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// SourceNodeID instead. It exists only for internal usage by the builders.
func (m *EdgeMutation) SourceNodeIDs() (ids []int) {
	if id := m.source_node; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSourceNode resets all changes to the "source_node" edge.
func (m *EdgeMutation) ResetSourceNode() {
	m.source_node = nil
	m.clearedsource_node = false
}

// SetTargetNodeID sets the "target_node" edge to the Node entity by id.
func (m *EdgeMutation) SetTargetNodeID(id int) {
	m.target_node = &id
}

// ClearTargetNode clears the "target_node" edge to the Node entity.
func (m *EdgeMutation) ClearTargetNode() {
	m.clearedtarget_node = true
}

// TargetNodeCleared reports if the "target_node" edge to the Node entity was cleared.
func (m *EdgeMutation) TargetNodeCleared() bool {
	return m.clearedtarget_node
}

// TargetNodeID returns the "target_node" edge ID in the mutation.
func (m *EdgeMutation) TargetNodeID() (id int, exists bool) {
	if m.target_node != nil {
		return *m.target_node, true
	}
	return
}

// TargetNodeIDs returns the "target_node" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TargetNodeID instead. It exists only for internal usage by the builders.
func (m *EdgeMutation) TargetNodeIDs() (ids []int) {
	if id := m.target_node; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTargetNode resets all changes to the "target_node" edge.
func (m *EdgeMutation) ResetTargetNode() {
	m.target_node = nil
	m.clearedtarget_node = false
}

// Where appends a list predicates to the EdgeMutation builder.
func (m *EdgeMutation) Where(ps ...predicate.Edge) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EdgeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EdgeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Edge, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EdgeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EdgeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Edge).
func (m *EdgeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EdgeMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.source_handle != nil {
		fields = append(fields, edge.FieldSourceHandle)
	}
	if m.target_handle != nil {
		fields = append(fields, edge.FieldTargetHandle)
	}
	if m.created_at != nil {
		fields = append(fields, edge.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EdgeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case edge.FieldSourceHandle:
		return m.SourceHandle()
	case edge.FieldTargetHandle:
		return m.TargetHandle()
	case edge.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EdgeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case edge.FieldSourceHandle:
		return m.OldSourceHandle(ctx)
	case edge.FieldTargetHandle:
		return m.OldTargetHandle(ctx)
	case edge.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Edge field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EdgeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case edge.FieldSourceHandle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceHandle(v)
		return nil
	case edge.FieldTargetHandle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetHandle(v)
		return nil
	case edge.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Edge field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EdgeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EdgeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EdgeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Edge numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EdgeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(edge.FieldSourceHandle) {
		fields = append(fields, edge.FieldSourceHandle)
	}
	if m.FieldCleared(edge.FieldTargetHandle) {
		fields = append(fields, edge.FieldTargetHandle)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EdgeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EdgeMutation) ClearField(name string) error {
	switch name {
	case edge.FieldSourceHandle:
		m.ClearSourceHandle()
		return nil
	case edge.FieldTargetHandle:
		m.ClearTargetHandle()
		return nil
	}
	return fmt.Errorf("unknown Edge nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EdgeMutation) ResetField(name string) error {
	switch name {
	case edge.FieldSourceHandle:
		m.ResetSourceHandle()
		return nil
	case edge.FieldTargetHandle:
		m.ResetTargetHandle()
		return nil
	case edge.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Edge field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EdgeMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.flow != nil {
		edges = append(edges, edge.EdgeFlow)
	}
	if m.source_node != nil {
		edges = append(edges, edge.EdgeSourceNode)
	}
	if m.target_node != nil {
		edges = append(edges, edge.EdgeTargetNode)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EdgeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case edge.EdgeFlow:
		if id := m.flow; id != nil {
			return []ent.Value{*id}
		}
	case edge.EdgeSourceNode:
		if id := m.source_node; id != nil {
			return []ent.Value{*id}
		}
	case edge.EdgeTargetNode:
		if id := m.target_node; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EdgeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EdgeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EdgeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedflow {
		edges = append(edges, edge.EdgeFlow)
	}
	if m.clearedsource_node {
		edges = append(edges, edge.EdgeSourceNode)
	}
	if m.clearedtarget_node {
		edges = append(edges, edge.EdgeTargetNode)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EdgeMutation) EdgeCleared(name string) bool {
	switch name {
	case edge.EdgeFlow:
		return m.clearedflow
	case edge.EdgeSourceNode:
		return m.clearedsource_node
	case edge.EdgeTargetNode:
		return m.clearedtarget_node
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EdgeMutation) ClearEdge(name string) error {
	switch name {
	case edge.EdgeFlow:
		m.ClearFlow()
		return nil
	case edge.EdgeSourceNode:
		m.ClearSourceNode()
		return nil
	case edge.EdgeTargetNode:
		m.ClearTargetNode()
		return nil
	}
	return fmt.Errorf("unknown Edge unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EdgeMutation) ResetEdge(name string) error {
	switch name {
	case edge.EdgeFlow:
		m.ResetFlow()
		return nil
	case edge.EdgeSourceNode:
		m.ResetSourceNode()
		return nil
	case edge.EdgeTargetNode:
		m.ResetTargetNode()
		return nil
	}
	return fmt.Errorf("unknown Edge edge %s", name)
}

// FlowMutation represents an operation that mutates the Flow nodes in the graph.
type FlowMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	description   *string
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	nodes         map[int]struct{}
	removednodes  map[int]struct{}
	clearednodes  bool
	edges         map[int]struct{}
	removededges  map[int]struct{}
	clearededges  bool
	done          bool
	oldValue      func(context.Context) (*Flow, error)
	predicates    []predicate.Flow
}

var _ ent.Mutation = (*FlowMutation)(nil)

// flowOption allows management of the mutation configuration using functional options.
type flowOption func(*FlowMutation)

// newFlowMutation creates new mutation for the Flow entity.
func newFlowMutation(c config, op Op, opts ...flowOption) *FlowMutation {
	m := &FlowMutation{
		config:        c,
		op:            op,
		typ:           TypeFlow,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFlowID sets the ID field of the mutation.
func withFlowID(id int) flowOption {
	return func(m *FlowMutation) {
		var (
			err   error
			once  sync.Once
			value *Flow
		)
		m.oldValue = func(ctx context.Context) (*Flow, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Flow.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFlow sets the old Flow of the mutation.
func withFlow(node *Flow) flowOption {
	return func(m *FlowMutation) {
		m.oldValue = func(context.Context) (*Flow, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FlowMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FlowMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FlowMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FlowMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Flow.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *FlowMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *FlowMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *FlowMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *FlowMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *FlowMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *FlowMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[flow.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *FlowMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[flow.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *FlowMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, flow.FieldDescription)
}

// SetCreatedAt sets the "created_at" field.
func (m *FlowMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *FlowMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *FlowMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *FlowMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *FlowMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *FlowMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddNodeIDs adds the "nodes" edge to the Node entity by ids.
func (m *FlowMutation) AddNodeIDs(ids ...int) {
	if m.nodes == nil {
		m.nodes = make(map[int]struct{})
	}
	for i := range ids {
		m.nodes[ids[i]] = struct{}{}
	}
}

// ClearNodes clears the "nodes" edge to the Node entity.
func (m *FlowMutation) ClearNodes() {
	m.clearednodes = true
}

// NodesCleared reports if the "nodes" edge to the Node entity was cleared.
func (m *FlowMutation) NodesCleared() bool {
	return m.clearednodes
}

// RemoveNodeIDs removes the "nodes" edge to the Node entity by IDs.
func (m *FlowMutation) RemoveNodeIDs(ids ...int) {
	if m.removednodes == nil {
		m.removednodes = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.nodes, ids[i])
		m.removednodes[ids[i]] = struct{}{}
	}
}

// RemovedNodes returns the removed IDs of the "nodes" edge to the Node entity.
func (m *FlowMutation) RemovedNodesIDs() (ids []int) {
	for id := range m.removednodes {
		ids = append(ids, id)
	}
	return
}

// NodesIDs returns the "nodes" edge IDs in the mutation.
func (m *FlowMutation) NodesIDs() (ids []int) {
	for id := range m.nodes {
		ids = append(ids, id)
	}
	return
}

// ResetNodes resets all changes to the "nodes" edge.
func (m *FlowMutation) ResetNodes() {
	m.nodes = nil
	m.clearednodes = false
	m.removednodes = nil
}

// AddEdgeIDs adds the "edges" edge to the Edge entity by ids.
func (m *FlowMutation) AddEdgeIDs(ids ...int) {
	if m.edges == nil {
		m.edges = make(map[int]struct{})
	}
	for i := range ids {
		m.edges[ids[i]] = struct{}{}
	}
}

// ClearEdges clears the "edges" edge to the Edge entity.
func (m *FlowMutation) ClearEdges() {
	m.clearededges = true
}

// EdgesCleared reports if the "edges" edge to the Edge entity was cleared.
func (m *FlowMutation) EdgesCleared() bool {
	return m.clearededges
}

// RemoveEdgeIDs removes the "edges" edge to the Edge entity by IDs.
func (m *FlowMutation) RemoveEdgeIDs(ids ...int) {
	if m.removededges == nil {
		m.removededges = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.edges, ids[i])
		m.removededges[ids[i]] = struct{}{}
	}
}

// RemovedEdges returns the removed IDs of the "edges" edge to the Edge entity.
func (m *FlowMutation) RemovedEdgesIDs() (ids []int) {
	for id := range m.removededges {
		ids = append(ids, id)
	}
	return
}

// EdgesIDs returns the "edges" edge IDs in the mutation.
func (m *FlowMutation) EdgesIDs() (ids []int) {
	for id := range m.edges {
		ids = append(ids, id)
	}
	return
}

// ResetEdges resets all changes to the "edges" edge.
func (m *FlowMutation) ResetEdges() {
	m.edges = nil
	m.clearededges = false
	m.removededges = nil
}

// Where appends a list predicates to the FlowMutation builder.
func (m *FlowMutation) Where(ps ...predicate.Flow) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FlowMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FlowMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Flow, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FlowMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FlowMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Flow).
func (m *FlowMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FlowMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, flow.FieldName)
	}
	if m.description != nil {
		fields = append(fields, flow.FieldDescription)
	}
	if m.created_at != nil {
		fields = append(fields, flow.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, flow.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FlowMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case flow.FieldName:
		return m.Name()
	case flow.FieldDescription:
		return m.Description()
	case flow.FieldCreatedAt:
		return m.CreatedAt()
	case flow.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FlowMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case flow.FieldName:
		return m.OldName(ctx)
	case flow.FieldDescription:
		return m.OldDescription(ctx)
	case flow.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case flow.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Flow field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlowMutation) SetField(name string, value ent.Value) error {
	switch name {
	case flow.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case flow.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case flow.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case flow.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Flow field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FlowMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FlowMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlowMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Flow numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FlowMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(flow.FieldDescription) {
		fields = append(fields, flow.FieldDescription)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FlowMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FlowMutation) ClearField(name string) error {
	switch name {
	case flow.FieldDescription:
		m.ClearDescription()
		return nil
	}
	return fmt.Errorf("unknown Flow nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FlowMutation) ResetField(name string) error {
	switch name {
	case flow.FieldName:
		m.ResetName()
		return nil
	case flow.FieldDescription:
		m.ResetDescription()
		return nil
	case flow.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case flow.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Flow field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FlowMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.nodes != nil {
		edges = append(edges, flow.EdgeNodes)
	}
	if m.edges != nil {
		edges = append(edges, flow.EdgeEdges)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FlowMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case flow.EdgeNodes:
		ids := make([]ent.Value, 0, len(m.nodes))
		for id := range m.nodes {
			ids = append(ids, id)
		}
		return ids
	case flow.EdgeEdges:
		ids := make([]ent.Value, 0, len(m.edges))
		for id := range m.edges {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FlowMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removednodes != nil {
		edges = append(edges, flow.EdgeNodes)
	}
	if m.removededges != nil {
		edges = append(edges, flow.EdgeEdges)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FlowMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case flow.EdgeNodes:
		ids := make([]ent.Value, 0, len(m.removednodes))
		for id := range m.removednodes {
			ids = append(ids, id)
		}
		return ids
	case flow.EdgeEdges:
		ids := make([]ent.Value, 0, len(m.removededges))
		for id := range m.removededges {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FlowMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearednodes {
		edges = append(edges, flow.EdgeNodes)
	}
	if m.clearededges {
		edges = append(edges, flow.EdgeEdges)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FlowMutation) EdgeCleared(name string) bool {
	switch name {
	case flow.EdgeNodes:
		return m.clearednodes
	case flow.EdgeEdges:
		return m.clearededges
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FlowMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Flow unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FlowMutation) ResetEdge(name string) error {
	switch name {
	case flow.EdgeNodes:
		m.ResetNodes()
		return nil
	case flow.EdgeEdges:
		m.ResetEdges()
		return nil
	}
	return fmt.Errorf("unknown Flow edge %s", name)
}

// NodeMutation represents an operation that mutates the Node nodes in the graph.
type NodeMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int
	_type                 *string
	data                  *map[string]interface{}
	position_x            *float64
	addposition_x         *float64
	position_y            *float64
	addposition_y         *float64
	created_at            *time.Time
	clearedFields         map[string]struct{}
	flow                  *int
	clearedflow           bool
	outgoing_edges        map[int]struct{}
	removedoutgoing_edges map[int]struct{}
	clearedoutgoing_edges bool
	incoming_edges        map[int]struct{}
	removedincoming_edges map[int]struct{}
	clearedincoming_edges bool
	done                  bool
	oldValue              func(context.Context) (*Node, error)
	predicates            []predicate.Node
}

var _ ent.Mutation = (*NodeMutation)(nil)

// nodeOption allows management of the mutation configuration using functional options.
type nodeOption func(*NodeMutation)

// newNodeMutation creates new mutation for the Node entity.
func newNodeMutation(c config, op Op, opts ...nodeOption) *NodeMutation {
	m := &NodeMutation{
		config:        c,
		op:            op,
		typ:           TypeNode,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNodeID sets the ID field of the mutation.
func withNodeID(id int) nodeOption {
	return func(m *NodeMutation) {
		var (
			err   error
			once  sync.Once
			value *Node
		)
		m.oldValue = func(ctx context.Context) (*Node, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Node.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNode sets the old Node of the mutation.
func withNode(node *Node) nodeOption {
	return func(m *NodeMutation) {
		m.oldValue = func(context.Context) (*Node, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NodeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NodeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NodeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NodeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Node.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetType sets the "type" field.
func (m *NodeMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *NodeMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *NodeMutation) ResetType() {
	m._type = nil
}

// SetData sets the "data" field.
func (m *NodeMutation) SetData(value map[string]interface{}) {
	m.data = &value
}

// Data returns the value of the "data" field in the mutation.
func (m *NodeMutation) Data() (r map[string]interface{}, exists bool) {
	v := m.data
	if v == nil {
		return
	}
	return *v, true
}

// OldData returns the old "data" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldData(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldData is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldData requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldData: %w", err)
	}
	return oldValue.Data, nil
}

// ClearData clears the value of the "data" field.
func (m *NodeMutation) ClearData() {
	m.data = nil
	m.clearedFields[node.FieldData] = struct{}{}
}

// DataCleared returns if the "data" field was cleared in this mutation.
func (m *NodeMutation) DataCleared() bool {
	_, ok := m.clearedFields[node.FieldData]
	return ok
}

// ResetData resets all changes to the "data" field.
func (m *NodeMutation) ResetData() {
	m.data = nil
	delete(m.clearedFields, node.FieldData)
}

// SetPositionX sets the "position_x" field.
func (m *NodeMutation) SetPositionX(f float64) {
	m.position_x = &f
	m.addposition_x = nil
}

// PositionX returns the value of the "position_x" field in the mutation.
func (m *NodeMutation) PositionX() (r float64, exists bool) {
	v := m.position_x
	if v == nil {
		return
	}
	return *v, true
}

// OldPositionX returns the old "position_x" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldPositionX(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPositionX is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPositionX requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPositionX: %w", err)
	}
	return oldValue.PositionX, nil
}

// AddPositionX adds f to the "position_x" field.
func (m *NodeMutation) AddPositionX(f float64) {
	if m.addposition_x != nil {
		*m.addposition_x += f
	} else {
		m.addposition_x = &f
	}
}

// AddedPositionX returns the value that was added to the "position_x" field in this mutation.
func (m *NodeMutation) AddedPositionX() (r float64, exists bool) {
	v := m.addposition_x
	if v == nil {
		return
	}
	return *v, true
}

// ResetPositionX resets all changes to the "position_x" field.
func (m *NodeMutation) ResetPositionX() {
	m.position_x = nil
	m.addposition_x = nil
}

// SetPositionY sets the "position_y" field.
func (m *NodeMutation) SetPositionY(f float64) {
	m.position_y = &f
	m.addposition_y = nil
}

// PositionY returns the value of the "position_y" field in the mutation.
func (m *NodeMutation) PositionY() (r float64, exists bool) {
	v := m.position_y
	if v == nil {
		return
	}
	return *v, true
}

// OldPositionY returns the old "position_y" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldPositionY(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPositionY is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPositionY requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPositionY: %w", err)
	}
	return oldValue.PositionY, nil
}

// AddPositionY adds f to the "position_y" field.
func (m *NodeMutation) AddPositionY(f float64) {
	if m.addposition_y != nil {
		*m.addposition_y += f
	} else {
		m.addposition_y = &f
	}
}

// AddedPositionY returns the value that was added to the "position_y" field in this mutation.
func (m *NodeMutation) AddedPositionY() (r float64, exists bool) {
	v := m.addposition_y
	if v == nil {
		return
	}
	return *v, true
}

// ResetPositionY resets all changes to the "position_y" field.
func (m *NodeMutation) ResetPositionY() {
	m.position_y = nil
	m.addposition_y = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *NodeMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *NodeMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *NodeMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetFlowID sets the "flow" edge to the Flow entity by id.
func (m *NodeMutation) SetFlowID(id int) {
	m.flow = &id
}

// ClearFlow clears the "flow" edge to the Flow entity.
func (m *NodeMutation) ClearFlow() {
	m.clearedflow = true
}

// FlowCleared reports if the "flow" edge to the Flow entity was cleared.
func (m *NodeMutation) FlowCleared() bool {
	return m.clearedflow
}

// FlowID returns the "flow" edge ID in the mutation.
func (m *NodeMutation) FlowID() (id int, exists bool) {
	if m.flow != nil {
		return *m.flow, true
	}
	return
}

// FlowIDs returns the "flow" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// FlowID instead. It exists only for internal usage by the builders.
func (m *NodeMutation) FlowIDs() (ids []int) {
	if id := m.flow; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFlow resets all changes to the "flow" edge.
func (m *NodeMutation) ResetFlow() {
	m.flow = nil
	m.clearedflow = false
}

// AddOutgoingEdgeIDs adds the "outgoing_edges" edge to the Edge entity by ids.
func (m *NodeMutation) AddOutgoingEdgeIDs(ids ...int) {
	if m.outgoing_edges == nil {
		m.outgoing_edges = make(map[int]struct{})
	}
	for i := range ids {
		m.outgoing_edges[ids[i]] = struct{}{}
	}
}

// ClearOutgoingEdges clears the "outgoing_edges" edge to the Edge entity.
func (m *NodeMutation) ClearOutgoingEdges() {
	m.clearedoutgoing_edges = true
}

// OutgoingEdgesCleared reports if the "outgoing_edges" edge to the Edge entity was cleared.
func (m *NodeMutation) OutgoingEdgesCleared() bool {
	return m.clearedoutgoing_edges
}

// RemoveOutgoingEdgeIDs removes the "outgoing_edges" edge to the Edge entity by IDs.
func (m *NodeMutation) RemoveOutgoingEdgeIDs(ids ...int) {
	if m.removedoutgoing_edges == nil {
		m.removedoutgoing_edges = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.outgoing_edges, ids[i])
		m.removedoutgoing_edges[ids[i]] = struct{}{}
	}
}

// RemovedOutgoingEdges returns the removed IDs of the "outgoing_edges" edge to the Edge entity.
func (m *NodeMutation) RemovedOutgoingEdgesIDs() (ids []int) {
	for id := range m.removedoutgoing_edges {
		ids = append(ids, id)
	}
	return
}

// OutgoingEdgesIDs returns the "outgoing_edges" edge IDs in the mutation.
func (m *NodeMutation) OutgoingEdgesIDs() (ids []int) {
	for id := range m.outgoing_edges {
		ids = append(ids, id)
	}
	return
}

// ResetOutgoingEdges resets all changes to the "outgoing_edges" edge.
func (m *NodeMutation) ResetOutgoingEdges() {
	m.outgoing_edges = nil
	m.clearedoutgoing_edges = false
	m.removedoutgoing_edges = nil
}

// AddIncomingEdgeIDs adds the "incoming_edges" edge to the Edge entity by ids.
func (m *NodeMutation) AddIncomingEdgeIDs(ids ...int) {
	if m.incoming_edges == nil {
		m.incoming_edges = make(map[int]struct{})
	}
	for i := range ids {
		m.incoming_edges[ids[i]] = struct{}{}
	}
}

// ClearIncomingEdges clears the "incoming_edges" edge to the Edge entity.
func (m *NodeMutation) ClearIncomingEdges() {
	m.clearedincoming_edges = true
}

// IncomingEdgesCleared reports if the "incoming_edges" edge to the Edge entity was cleared.
func (m *NodeMutation) IncomingEdgesCleared() bool {
	return m.clearedincoming_edges
}

// RemoveIncomingEdgeIDs removes the "incoming_edges" edge to the Edge entity by IDs.
func (m *NodeMutation) RemoveIncomingEdgeIDs(ids ...int) {
	if m.removedincoming_edges == nil {
		m.removedincoming_edges = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.incoming_edges, ids[i])
		m.removedincoming_edges[ids[i]] = struct{}{}
	}
}

// RemovedIncomingEdges returns the removed IDs of the "incoming_edges" edge to the Edge entity.
func (m *NodeMutation) RemovedIncomingEdgesIDs() (ids []int) {
	for id := range m.removedincoming_edges {
		ids = append(ids, id)
	}
	return
}

// IncomingEdgesIDs returns the "incoming_edges" edge IDs in the mutation.
func (m *NodeMutation) IncomingEdgesIDs() (ids []int) {
	for id := range m.incoming_edges {
		ids = append(ids, id)
	}
	return
}

// ResetIncomingEdges resets all changes to the "incoming_edges" edge.
func (m *NodeMutation) ResetIncomingEdges() {
	m.incoming_edges = nil
	m.clearedincoming_edges = false
	m.removedincoming_edges = nil
}

// Where appends a list predicates to the NodeMutation builder.
func (m *NodeMutation) Where(ps ...predicate.Node) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NodeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NodeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Node, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NodeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NodeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Node).
func (m *NodeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NodeMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m._type != nil {
		fields = append(fields, node.FieldType)
	}
	if m.data != nil {
		fields = append(fields, node.FieldData)
	}
	if m.position_x != nil {
		fields = append(fields, node.FieldPositionX)
	}
	if m.position_y != nil {
		fields = append(fields, node.FieldPositionY)
	}
	if m.created_at != nil {
		fields = append(fields, node.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NodeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case node.FieldType:
		return m.GetType()
	case node.FieldData:
		return m.Data()
	case node.FieldPositionX:
		return m.PositionX()
	case node.FieldPositionY:
		return m.PositionY()
	case node.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NodeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case node.FieldType:
		return m.OldType(ctx)
	case node.FieldData:
		return m.OldData(ctx)
	case node.FieldPositionX:
		return m.OldPositionX(ctx)
	case node.FieldPositionY:
		return m.OldPositionY(ctx)
	case node.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Node field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NodeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case node.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case node.FieldData:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetData(v)
		return nil
	case node.FieldPositionX:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPositionX(v)
		return nil
	case node.FieldPositionY:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPositionY(v)
		return nil
	case node.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Node field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NodeMutation) AddedFields() []string {
	var fields []string
	if m.addposition_x != nil {
		fields = append(fields, node.FieldPositionX)
	}
	if m.addposition_y != nil {
		fields = append(fields, node.FieldPositionY)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NodeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case node.FieldPositionX:
		return m.AddedPositionX()
	case node.FieldPositionY:
		return m.AddedPositionY()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NodeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case node.FieldPositionX:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPositionX(v)
		return nil
	case node.FieldPositionY:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPositionY(v)
		return nil
	}
	return fmt.Errorf("unknown Node numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NodeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(node.FieldData) {
		fields = append(fields, node.FieldData)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NodeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NodeMutation) ClearField(name string) error {
	switch name {
	case node.FieldData:
		m.ClearData()
		return nil
	}
	return fmt.Errorf("unknown Node nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NodeMutation) ResetField(name string) error {
	switch name {
	case node.FieldType:
		m.ResetType()
		return nil
	case node.FieldData:
		m.ResetData()
		return nil
	case node.FieldPositionX:
		m.ResetPositionX()
		return nil
	case node.FieldPositionY:
		m.ResetPositionY()
		return nil
	case node.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Node field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NodeMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.flow != nil {
		edges = append(edges, node.EdgeFlow)
	}
	if m.outgoing_edges != nil {
		edges = append(edges, node.EdgeOutgoingEdges)
	}
	if m.incoming_edges != nil {
		edges = append(edges, node.EdgeIncomingEdges)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NodeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case node.EdgeFlow:
		if id := m.flow; id != nil {
			return []ent.Value{*id}
		}
	case node.EdgeOutgoingEdges:
		ids := make([]ent.Value, 0, len(m.outgoing_edges))
		for id := range m.outgoing_edges {
			ids = append(ids, id)
		}
		return ids
	case node.EdgeIncomingEdges:
		ids := make([]ent.Value, 0, len(m.incoming_edges))
		for id := range m.incoming_edges {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NodeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedoutgoing_edges != nil {
		edges = append(edges, node.EdgeOutgoingEdges)
	}
	if m.removedincoming_edges != nil {
		edges = append(edges, node.EdgeIncomingEdges)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NodeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case node.EdgeOutgoingEdges:
		ids := make([]ent.Value, 0, len(m.removedoutgoing_edges))
		for id := range m.removedoutgoing_edges {
			ids = append(ids, id)
		}
		return ids
	case node.EdgeIncomingEdges:
		ids := make([]ent.Value, 0, len(m.removedincoming_edges))
		for id := range m.removedincoming_edges {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NodeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedflow {
		edges = append(edges, node.EdgeFlow)
	}
	if m.clearedoutgoing_edges {
		edges = append(edges, node.EdgeOutgoingEdges)
	}
	if m.clearedincoming_edges {
		edges = append(edges, node.EdgeIncomingEdges)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NodeMutation) EdgeCleared(name string) bool {
	switch name {
	case node.EdgeFlow:
		return m.clearedflow
	case node.EdgeOutgoingEdges:
		return m.clearedoutgoing_edges
	case node.EdgeIncomingEdges:
		return m.clearedincoming_edges
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NodeMutation) ClearEdge(name string) error {
	switch name {
	case node.EdgeFlow:
		m.ClearFlow()
		return nil
	}
	return fmt.Errorf("unknown Node unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NodeMutation) ResetEdge(name string) error {
	switch name {
	case node.EdgeFlow:
		m.ResetFlow()
		return nil
	case node.EdgeOutgoingEdges:
		m.ResetOutgoingEdges()
		return nil
	case node.EdgeIncomingEdges:
		m.ResetIncomingEdges()
		return nil
	}
	return fmt.Errorf("unknown Node edge %s", name)
}
