// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"sipflow/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *NodeUpdate) SetType(v string) *NodeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableType(v *string) *NodeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetXyflowID sets the "xyflow_id" field.
func (_u *NodeUpdate) SetXyflowID(v string) *NodeUpdate {
	_u.mutation.SetXyflowID(v)
	return _u
}

// SetNillableXyflowID sets the "xyflow_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableXyflowID(v *string) *NodeUpdate {
	if v != nil {
		_u.SetXyflowID(*v)
	}
	return _u
}

// ClearXyflowID clears the value of the "xyflow_id" field.
func (_u *NodeUpdate) ClearXyflowID() *NodeUpdate {
	_u.mutation.ClearXyflowID()
	return _u
}

// SetData sets the "data" field.
func (_u *NodeUpdate) SetData(v map[string]interface{}) *NodeUpdate {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *NodeUpdate) ClearData() *NodeUpdate {
	_u.mutation.ClearData()
	return _u
}

// SetPositionX sets the "position_x" field.
func (_u *NodeUpdate) SetPositionX(v float64) *NodeUpdate {
	_u.mutation.ResetPositionX()
	_u.mutation.SetPositionX(v)
	return _u
}

// SetNillablePositionX sets the "position_x" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePositionX(v *float64) *NodeUpdate {
	if v != nil {
		_u.SetPositionX(*v)
	}
	return _u
}

// AddPositionX adds value to the "position_x" field.
func (_u *NodeUpdate) AddPositionX(v float64) *NodeUpdate {
	_u.mutation.AddPositionX(v)
	return _u
}

// SetPositionY sets the "position_y" field.
func (_u *NodeUpdate) SetPositionY(v float64) *NodeUpdate {
	_u.mutation.ResetPositionY()
	_u.mutation.SetPositionY(v)
	return _u
}

// SetNillablePositionY sets the "position_y" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePositionY(v *float64) *NodeUpdate {
	if v != nil {
		_u.SetPositionY(*v)
	}
	return _u
}

// AddPositionY adds value to the "position_y" field.
func (_u *NodeUpdate) AddPositionY(v float64) *NodeUpdate {
	_u.mutation.AddPositionY(v)
	return _u
}

// SetFlowID sets the "flow" edge to the Flow entity by ID.
func (_u *NodeUpdate) SetFlowID(id int) *NodeUpdate {
	_u.mutation.SetFlowID(id)
	return _u
}

// SetFlow sets the "flow" edge to the Flow entity.
func (_u *NodeUpdate) SetFlow(v *Flow) *NodeUpdate {
	return _u.SetFlowID(v.ID)
}

// AddOutgoingEdgeIDs adds the "outgoing_edges" edge to the Edge entity by IDs.
func (_u *NodeUpdate) AddOutgoingEdgeIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddOutgoingEdgeIDs(ids...)
	return _u
}

// AddOutgoingEdges adds the "outgoing_edges" edges to the Edge entity.
func (_u *NodeUpdate) AddOutgoingEdges(v ...*Edge) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutgoingEdgeIDs(ids...)
}

// AddIncomingEdgeIDs adds the "incoming_edges" edge to the Edge entity by IDs.
func (_u *NodeUpdate) AddIncomingEdgeIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddIncomingEdgeIDs(ids...)
	return _u
}

// AddIncomingEdges adds the "incoming_edges" edges to the Edge entity.
func (_u *NodeUpdate) AddIncomingEdges(v ...*Edge) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncomingEdgeIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearFlow clears the "flow" edge to the Flow entity.
func (_u *NodeUpdate) ClearFlow() *NodeUpdate {
	_u.mutation.ClearFlow()
	return _u
}

// ClearOutgoingEdges clears all "outgoing_edges" edges to the Edge entity.
func (_u *NodeUpdate) ClearOutgoingEdges() *NodeUpdate {
	_u.mutation.ClearOutgoingEdges()
	return _u
}

// RemoveOutgoingEdgeIDs removes the "outgoing_edges" edge to Edge entities by IDs.
func (_u *NodeUpdate) RemoveOutgoingEdgeIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveOutgoingEdgeIDs(ids...)
	return _u
}

// RemoveOutgoingEdges removes "outgoing_edges" edges to Edge entities.
func (_u *NodeUpdate) RemoveOutgoingEdges(v ...*Edge) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutgoingEdgeIDs(ids...)
}

// ClearIncomingEdges clears all "incoming_edges" edges to the Edge entity.
func (_u *NodeUpdate) ClearIncomingEdges() *NodeUpdate {
	_u.mutation.ClearIncomingEdges()
	return _u
}

// RemoveIncomingEdgeIDs removes the "incoming_edges" edge to Edge entities by IDs.
func (_u *NodeUpdate) RemoveIncomingEdgeIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveIncomingEdgeIDs(ids...)
	return _u
}

// RemoveIncomingEdges removes "incoming_edges" edges to Edge entities.
func (_u *NodeUpdate) RemoveIncomingEdges(v ...*Edge) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncomingEdgeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := node.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Node.type": %w`, err)}
		}
	}
	if _u.mutation.FlowCleared() && len(_u.mutation.FlowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Node.flow"`)
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.XyflowID(); ok {
		_spec.SetField(node.FieldXyflowID, field.TypeString, value)
	}
	if _u.mutation.XyflowIDCleared() {
		_spec.ClearField(node.FieldXyflowID, field.TypeString)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(node.FieldData, field.TypeJSON, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(node.FieldData, field.TypeJSON)
	}
	if value, ok := _u.mutation.PositionX(); ok {
		_spec.SetField(node.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionX(); ok {
		_spec.AddField(node.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PositionY(); ok {
		_spec.SetField(node.FieldPositionY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionY(); ok {
		_spec.AddField(node.FieldPositionY, field.TypeFloat64, value)
	}
	if _u.mutation.FlowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.FlowTable,
			Columns: []string{node.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.FlowTable,
			Columns: []string{node.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutgoingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingEdgesTable,
			Columns: []string{node.OutgoingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutgoingEdgesIDs(); len(nodes) > 0 && !_u.mutation.OutgoingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingEdgesTable,
			Columns: []string{node.OutgoingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutgoingEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingEdgesTable,
			Columns: []string{node.OutgoingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncomingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingEdgesTable,
			Columns: []string{node.IncomingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncomingEdgesIDs(); len(nodes) > 0 && !_u.mutation.IncomingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingEdgesTable,
			Columns: []string{node.IncomingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncomingEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingEdgesTable,
			Columns: []string{node.IncomingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetType sets the "type" field.
func (_u *NodeUpdateOne) SetType(v string) *NodeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableType(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetXyflowID sets the "xyflow_id" field.
func (_u *NodeUpdateOne) SetXyflowID(v string) *NodeUpdateOne {
	_u.mutation.SetXyflowID(v)
	return _u
}

// SetNillableXyflowID sets the "xyflow_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableXyflowID(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetXyflowID(*v)
	}
	return _u
}

// ClearXyflowID clears the value of the "xyflow_id" field.
func (_u *NodeUpdateOne) ClearXyflowID() *NodeUpdateOne {
	_u.mutation.ClearXyflowID()
	return _u
}

// SetData sets the "data" field.
func (_u *NodeUpdateOne) SetData(v map[string]interface{}) *NodeUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *NodeUpdateOne) ClearData() *NodeUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// SetPositionX sets the "position_x" field.
func (_u *NodeUpdateOne) SetPositionX(v float64) *NodeUpdateOne {
	_u.mutation.ResetPositionX()
	_u.mutation.SetPositionX(v)
	return _u
}

// SetNillablePositionX sets the "position_x" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePositionX(v *float64) *NodeUpdateOne {
	if v != nil {
		_u.SetPositionX(*v)
	}
	return _u
}

// AddPositionX adds value to the "position_x" field.
func (_u *NodeUpdateOne) AddPositionX(v float64) *NodeUpdateOne {
	_u.mutation.AddPositionX(v)
	return _u
}

// SetPositionY sets the "position_y" field.
func (_u *NodeUpdateOne) SetPositionY(v float64) *NodeUpdateOne {
	_u.mutation.ResetPositionY()
	_u.mutation.SetPositionY(v)
	return _u
}

// SetNillablePositionY sets the "position_y" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePositionY(v *float64) *NodeUpdateOne {
	if v != nil {
		_u.SetPositionY(*v)
	}
	return _u
}

// AddPositionY adds value to the "position_y" field.
func (_u *NodeUpdateOne) AddPositionY(v float64) *NodeUpdateOne {
	_u.mutation.AddPositionY(v)
	return _u
}

// SetFlowID sets the "flow" edge to the Flow entity by ID.
func (_u *NodeUpdateOne) SetFlowID(id int) *NodeUpdateOne {
	_u.mutation.SetFlowID(id)
	return _u
}

// SetFlow sets the "flow" edge to the Flow entity.
func (_u *NodeUpdateOne) SetFlow(v *Flow) *NodeUpdateOne {
	return _u.SetFlowID(v.ID)
}

// AddOutgoingEdgeIDs adds the "outgoing_edges" edge to the Edge entity by IDs.
func (_u *NodeUpdateOne) AddOutgoingEdgeIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddOutgoingEdgeIDs(ids...)
	return _u
}

// AddOutgoingEdges adds the "outgoing_edges" edges to the Edge entity.
func (_u *NodeUpdateOne) AddOutgoingEdges(v ...*Edge) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutgoingEdgeIDs(ids...)
}

// AddIncomingEdgeIDs adds the "incoming_edges" edge to the Edge entity by IDs.
func (_u *NodeUpdateOne) AddIncomingEdgeIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddIncomingEdgeIDs(ids...)
	return _u
}

// AddIncomingEdges adds the "incoming_edges" edges to the Edge entity.
func (_u *NodeUpdateOne) AddIncomingEdges(v ...*Edge) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncomingEdgeIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearFlow clears the "flow" edge to the Flow entity.
func (_u *NodeUpdateOne) ClearFlow() *NodeUpdateOne {
	_u.mutation.ClearFlow()
	return _u
}

// ClearOutgoingEdges clears all "outgoing_edges" edges to the Edge entity.
func (_u *NodeUpdateOne) ClearOutgoingEdges() *NodeUpdateOne {
	_u.mutation.ClearOutgoingEdges()
	return _u
}

// RemoveOutgoingEdgeIDs removes the "outgoing_edges" edge to Edge entities by IDs.
func (_u *NodeUpdateOne) RemoveOutgoingEdgeIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveOutgoingEdgeIDs(ids...)
	return _u
}

// RemoveOutgoingEdges removes "outgoing_edges" edges to Edge entities.
func (_u *NodeUpdateOne) RemoveOutgoingEdges(v ...*Edge) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutgoingEdgeIDs(ids...)
}

// ClearIncomingEdges clears all "incoming_edges" edges to the Edge entity.
func (_u *NodeUpdateOne) ClearIncomingEdges() *NodeUpdateOne {
	_u.mutation.ClearIncomingEdges()
	return _u
}

// RemoveIncomingEdgeIDs removes the "incoming_edges" edge to Edge entities by IDs.
func (_u *NodeUpdateOne) RemoveIncomingEdgeIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveIncomingEdgeIDs(ids...)
	return _u
}

// RemoveIncomingEdges removes "incoming_edges" edges to Edge entities.
func (_u *NodeUpdateOne) RemoveIncomingEdges(v ...*Edge) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncomingEdgeIDs(ids...)
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := node.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Node.type": %w`, err)}
		}
	}
	if _u.mutation.FlowCleared() && len(_u.mutation.FlowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Node.flow"`)
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.XyflowID(); ok {
		_spec.SetField(node.FieldXyflowID, field.TypeString, value)
	}
	if _u.mutation.XyflowIDCleared() {
		_spec.ClearField(node.FieldXyflowID, field.TypeString)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(node.FieldData, field.TypeJSON, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(node.FieldData, field.TypeJSON)
	}
	if value, ok := _u.mutation.PositionX(); ok {
		_spec.SetField(node.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionX(); ok {
		_spec.AddField(node.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PositionY(); ok {
		_spec.SetField(node.FieldPositionY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionY(); ok {
		_spec.AddField(node.FieldPositionY, field.TypeFloat64, value)
	}
	if _u.mutation.FlowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.FlowTable,
			Columns: []string{node.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.FlowTable,
			Columns: []string{node.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutgoingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingEdgesTable,
			Columns: []string{node.OutgoingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutgoingEdgesIDs(); len(nodes) > 0 && !_u.mutation.OutgoingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingEdgesTable,
			Columns: []string{node.OutgoingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutgoingEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingEdgesTable,
			Columns: []string{node.OutgoingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncomingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingEdgesTable,
			Columns: []string{node.IncomingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncomingEdgesIDs(); len(nodes) > 0 && !_u.mutation.IncomingEdgesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingEdgesTable,
			Columns: []string{node.IncomingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncomingEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingEdgesTable,
			Columns: []string{node.IncomingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
