// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NodeCreate is the builder for creating a Node entity.
type NodeCreate struct {
	config
	mutation *NodeMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *NodeCreate) SetType(v string) *NodeCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetXyflowID sets the "xyflow_id" field.
func (_c *NodeCreate) SetXyflowID(v string) *NodeCreate {
	_c.mutation.SetXyflowID(v)
	return _c
}

// SetNillableXyflowID sets the "xyflow_id" field if the given value is not nil.
func (_c *NodeCreate) SetNillableXyflowID(v *string) *NodeCreate {
	if v != nil {
		_c.SetXyflowID(*v)
	}
	return _c
}

// SetData sets the "data" field.
func (_c *NodeCreate) SetData(v map[string]interface{}) *NodeCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetPositionX sets the "position_x" field.
func (_c *NodeCreate) SetPositionX(v float64) *NodeCreate {
	_c.mutation.SetPositionX(v)
	return _c
}

// SetNillablePositionX sets the "position_x" field if the given value is not nil.
func (_c *NodeCreate) SetNillablePositionX(v *float64) *NodeCreate {
	if v != nil {
		_c.SetPositionX(*v)
	}
	return _c
}

// SetPositionY sets the "position_y" field.
func (_c *NodeCreate) SetPositionY(v float64) *NodeCreate {
	_c.mutation.SetPositionY(v)
	return _c
}

// SetNillablePositionY sets the "position_y" field if the given value is not nil.
func (_c *NodeCreate) SetNillablePositionY(v *float64) *NodeCreate {
	if v != nil {
		_c.SetPositionY(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NodeCreate) SetCreatedAt(v time.Time) *NodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NodeCreate) SetNillableCreatedAt(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetFlowID sets the "flow" edge to the Flow entity by ID.
func (_c *NodeCreate) SetFlowID(id int) *NodeCreate {
	_c.mutation.SetFlowID(id)
	return _c
}

// SetFlow sets the "flow" edge to the Flow entity.
func (_c *NodeCreate) SetFlow(v *Flow) *NodeCreate {
	return _c.SetFlowID(v.ID)
}

// AddOutgoingEdgeIDs adds the "outgoing_edges" edge to the Edge entity by IDs.
func (_c *NodeCreate) AddOutgoingEdgeIDs(ids ...int) *NodeCreate {
	_c.mutation.AddOutgoingEdgeIDs(ids...)
	return _c
}

// AddOutgoingEdges adds the "outgoing_edges" edges to the Edge entity.
func (_c *NodeCreate) AddOutgoingEdges(v ...*Edge) *NodeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOutgoingEdgeIDs(ids...)
}

// AddIncomingEdgeIDs adds the "incoming_edges" edge to the Edge entity by IDs.
func (_c *NodeCreate) AddIncomingEdgeIDs(ids ...int) *NodeCreate {
	_c.mutation.AddIncomingEdgeIDs(ids...)
	return _c
}

// AddIncomingEdges adds the "incoming_edges" edges to the Edge entity.
func (_c *NodeCreate) AddIncomingEdges(v ...*Edge) *NodeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIncomingEdgeIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (_c *NodeCreate) Mutation() *NodeMutation {
	return _c.mutation
}

// Save creates the Node in the database.
func (_c *NodeCreate) Save(ctx context.Context) (*Node, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeCreate) SaveX(ctx context.Context) *Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NodeCreate) defaults() {
	if _, ok := _c.mutation.XyflowID(); !ok {
		v := node.DefaultXyflowID
		_c.mutation.SetXyflowID(v)
	}
	if _, ok := _c.mutation.PositionX(); !ok {
		v := node.DefaultPositionX
		_c.mutation.SetPositionX(v)
	}
	if _, ok := _c.mutation.PositionY(); !ok {
		v := node.DefaultPositionY
		_c.mutation.SetPositionY(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := node.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Node.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := node.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Node.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PositionX(); !ok {
		return &ValidationError{Name: "position_x", err: errors.New(`ent: missing required field "Node.position_x"`)}
	}
	if _, ok := _c.mutation.PositionY(); !ok {
		return &ValidationError{Name: "position_y", err: errors.New(`ent: missing required field "Node.position_y"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Node.created_at"`)}
	}
	if len(_c.mutation.FlowIDs()) == 0 {
		return &ValidationError{Name: "flow", err: errors.New(`ent: missing required edge "Node.flow"`)}
	}
	return nil
}

func (_c *NodeCreate) sqlSave(ctx context.Context) (*Node, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeCreate) createSpec() (*Node, *sqlgraph.CreateSpec) {
	var (
		_node = &Node{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(node.Table, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.XyflowID(); ok {
		_spec.SetField(node.FieldXyflowID, field.TypeString, value)
		_node.XyflowID = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(node.FieldData, field.TypeJSON, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.PositionX(); ok {
		_spec.SetField(node.FieldPositionX, field.TypeFloat64, value)
		_node.PositionX = value
	}
	if value, ok := _c.mutation.PositionY(); ok {
		_spec.SetField(node.FieldPositionY, field.TypeFloat64, value)
		_node.PositionY = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.FlowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.FlowTable,
			Columns: []string{node.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.flow_nodes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OutgoingEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingEdgesTable,
			Columns: []string{node.OutgoingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IncomingEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingEdgesTable,
			Columns: []string{node.IncomingEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NodeCreateBulk is the builder for creating many Node entities in bulk.
type NodeCreateBulk struct {
	config
	err      error
	builders []*NodeCreate
}

// Save creates the Node entities in the database.
func (_c *NodeCreateBulk) Save(ctx context.Context) ([]*Node, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Node, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeCreateBulk) SaveX(ctx context.Context) []*Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
