// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Node is the model entity for the Node schema.
type Node struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Data holds the value of the "data" field.
	Data map[string]interface{} `json:"data,omitempty"`
	// PositionX holds the value of the "position_x" field.
	PositionX float64 `json:"position_x,omitempty"`
	// PositionY holds the value of the "position_y" field.
	PositionY float64 `json:"position_y,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeQuery when eager-loading is set.
	Edges        NodeEdges `json:"edges"`
	flow_nodes   *int
	selectValues sql.SelectValues
}

// NodeEdges holds the relations/edges for other nodes in the graph.
type NodeEdges struct {
	// Flow holds the value of the flow edge.
	Flow *Flow `json:"flow,omitempty"`
	// OutgoingEdges holds the value of the outgoing_edges edge.
	OutgoingEdges []*Edge `json:"outgoing_edges,omitempty"`
	// IncomingEdges holds the value of the incoming_edges edge.
	IncomingEdges []*Edge `json:"incoming_edges,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// FlowOrErr returns the Flow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) FlowOrErr() (*Flow, error) {
	if e.Flow != nil {
		return e.Flow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: flow.Label}
	}
	return nil, &NotLoadedError{edge: "flow"}
}

// OutgoingEdgesOrErr returns the OutgoingEdges value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) OutgoingEdgesOrErr() ([]*Edge, error) {
	if e.loadedTypes[1] {
		return e.OutgoingEdges, nil
	}
	return nil, &NotLoadedError{edge: "outgoing_edges"}
}

// IncomingEdgesOrErr returns the IncomingEdges value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) IncomingEdgesOrErr() ([]*Edge, error) {
	if e.loadedTypes[2] {
		return e.IncomingEdges, nil
	}
	return nil, &NotLoadedError{edge: "incoming_edges"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Node) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case node.FieldData:
			values[i] = new([]byte)
		case node.FieldPositionX, node.FieldPositionY:
			values[i] = new(sql.NullFloat64)
		case node.FieldID:
			values[i] = new(sql.NullInt64)
		case node.FieldType:
			values[i] = new(sql.NullString)
		case node.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case node.ForeignKeys[0]: // flow_nodes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Node fields.
func (_m *Node) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case node.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case node.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case node.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Data); err != nil {
					return fmt.Errorf("unmarshal field data: %w", err)
				}
			}
		case node.FieldPositionX:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position_x", values[i])
			} else if value.Valid {
				_m.PositionX = value.Float64
			}
		case node.FieldPositionY:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position_y", values[i])
			} else if value.Valid {
				_m.PositionY = value.Float64
			}
		case node.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case node.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field flow_nodes", value)
			} else if value.Valid {
				_m.flow_nodes = new(int)
				*_m.flow_nodes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Node.
// This includes values selected through modifiers, order, etc.
func (_m *Node) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFlow queries the "flow" edge of the Node entity.
func (_m *Node) QueryFlow() *FlowQuery {
	return NewNodeClient(_m.config).QueryFlow(_m)
}

// QueryOutgoingEdges queries the "outgoing_edges" edge of the Node entity.
func (_m *Node) QueryOutgoingEdges() *EdgeQuery {
	return NewNodeClient(_m.config).QueryOutgoingEdges(_m)
}

// QueryIncomingEdges queries the "incoming_edges" edge of the Node entity.
func (_m *Node) QueryIncomingEdges() *EdgeQuery {
	return NewNodeClient(_m.config).QueryIncomingEdges(_m)
}

// Update returns a builder for updating this Node.
// Note that you need to call Node.Unwrap() before calling this method if this Node
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Node) Update() *NodeUpdateOne {
	return NewNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Node entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Node) Unwrap() *Node {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Node is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Node) String() string {
	var builder strings.Builder
	builder.WriteString("Node(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteString(", ")
	builder.WriteString("position_x=")
	builder.WriteString(fmt.Sprintf("%v", _m.PositionX))
	builder.WriteString(", ")
	builder.WriteString("position_y=")
	builder.WriteString(fmt.Sprintf("%v", _m.PositionY))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Nodes is a parsable slice of Node.
type Nodes []*Node
