// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"sipflow/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	edgeFields := schema.Edge{}.Fields()
	_ = edgeFields
	// edgeDescSourceHandle is the schema descriptor for source_handle field.
	edgeDescSourceHandle := edgeFields[0].Descriptor()
	// edge.DefaultSourceHandle holds the default value on creation for the source_handle field.
	edge.DefaultSourceHandle = edgeDescSourceHandle.Default.(string)
	// edgeDescTargetHandle is the schema descriptor for target_handle field.
	edgeDescTargetHandle := edgeFields[1].Descriptor()
	// edge.DefaultTargetHandle holds the default value on creation for the target_handle field.
	edge.DefaultTargetHandle = edgeDescTargetHandle.Default.(string)
	// edgeDescCreatedAt is the schema descriptor for created_at field.
	edgeDescCreatedAt := edgeFields[2].Descriptor()
	// edge.DefaultCreatedAt holds the default value on creation for the created_at field.
	edge.DefaultCreatedAt = edgeDescCreatedAt.Default.(func() time.Time)
	flowFields := schema.Flow{}.Fields()
	_ = flowFields
	// flowDescName is the schema descriptor for name field.
	flowDescName := flowFields[0].Descriptor()
	// flow.NameValidator is a validator for the "name" field. It is called by the builders before save.
	flow.NameValidator = flowDescName.Validators[0].(func(string) error)
	// flowDescDescription is the schema descriptor for description field.
	flowDescDescription := flowFields[1].Descriptor()
	// flow.DefaultDescription holds the default value on creation for the description field.
	flow.DefaultDescription = flowDescDescription.Default.(string)
	// flowDescCreatedAt is the schema descriptor for created_at field.
	flowDescCreatedAt := flowFields[2].Descriptor()
	// flow.DefaultCreatedAt holds the default value on creation for the created_at field.
	flow.DefaultCreatedAt = flowDescCreatedAt.Default.(func() time.Time)
	// flowDescUpdatedAt is the schema descriptor for updated_at field.
	flowDescUpdatedAt := flowFields[3].Descriptor()
	// flow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flow.DefaultUpdatedAt = flowDescUpdatedAt.Default.(func() time.Time)
	// flow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flow.UpdateDefaultUpdatedAt = flowDescUpdatedAt.UpdateDefault.(func() time.Time)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescType is the schema descriptor for type field.
	nodeDescType := nodeFields[0].Descriptor()
	// node.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	node.TypeValidator = nodeDescType.Validators[0].(func(string) error)
	// nodeDescPositionX is the schema descriptor for position_x field.
	nodeDescPositionX := nodeFields[2].Descriptor()
	// node.DefaultPositionX holds the default value on creation for the position_x field.
	node.DefaultPositionX = nodeDescPositionX.Default.(float64)
	// nodeDescPositionY is the schema descriptor for position_y field.
	nodeDescPositionY := nodeFields[3].Descriptor()
	// node.DefaultPositionY holds the default value on creation for the position_y field.
	node.DefaultPositionY = nodeDescPositionY.Default.(float64)
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[4].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
}
