// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sipflow/ent/edge"
	"sipflow/ent/flow"
	"sipflow/ent/node"
	"sipflow/ent/schema"
	"sipflow/ent/sipserver"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	edgeFields := schema.Edge{}.Fields()
	_ = edgeFields
	// edgeDescXyflowID is the schema descriptor for xyflow_id field.
	edgeDescXyflowID := edgeFields[0].Descriptor()
	// edge.DefaultXyflowID holds the default value on creation for the xyflow_id field.
	edge.DefaultXyflowID = edgeDescXyflowID.Default.(string)
	// edgeDescType is the schema descriptor for type field.
	edgeDescType := edgeFields[1].Descriptor()
	// edge.DefaultType holds the default value on creation for the type field.
	edge.DefaultType = edgeDescType.Default.(string)
	// edgeDescSourceHandle is the schema descriptor for source_handle field.
	edgeDescSourceHandle := edgeFields[2].Descriptor()
	// edge.DefaultSourceHandle holds the default value on creation for the source_handle field.
	edge.DefaultSourceHandle = edgeDescSourceHandle.Default.(string)
	// edgeDescTargetHandle is the schema descriptor for target_handle field.
	edgeDescTargetHandle := edgeFields[3].Descriptor()
	// edge.DefaultTargetHandle holds the default value on creation for the target_handle field.
	edge.DefaultTargetHandle = edgeDescTargetHandle.Default.(string)
	// edgeDescCreatedAt is the schema descriptor for created_at field.
	edgeDescCreatedAt := edgeFields[5].Descriptor()
	// edge.DefaultCreatedAt holds the default value on creation for the created_at field.
	edge.DefaultCreatedAt = edgeDescCreatedAt.Default.(func() time.Time)
	flowFields := schema.Flow{}.Fields()
	_ = flowFields
	// flowDescName is the schema descriptor for name field.
	flowDescName := flowFields[0].Descriptor()
	// flow.NameValidator is a validator for the "name" field. It is called by the builders before save.
	flow.NameValidator = flowDescName.Validators[0].(func(string) error)
	// flowDescDescription is the schema descriptor for description field.
	flowDescDescription := flowFields[1].Descriptor()
	// flow.DefaultDescription holds the default value on creation for the description field.
	flow.DefaultDescription = flowDescDescription.Default.(string)
	// flowDescViewportX is the schema descriptor for viewport_x field.
	flowDescViewportX := flowFields[2].Descriptor()
	// flow.DefaultViewportX holds the default value on creation for the viewport_x field.
	flow.DefaultViewportX = flowDescViewportX.Default.(float64)
	// flowDescViewportY is the schema descriptor for viewport_y field.
	flowDescViewportY := flowFields[3].Descriptor()
	// flow.DefaultViewportY holds the default value on creation for the viewport_y field.
	flow.DefaultViewportY = flowDescViewportY.Default.(float64)
	// flowDescViewportZoom is the schema descriptor for viewport_zoom field.
	flowDescViewportZoom := flowFields[4].Descriptor()
	// flow.DefaultViewportZoom holds the default value on creation for the viewport_zoom field.
	flow.DefaultViewportZoom = flowDescViewportZoom.Default.(float64)
	// flowDescCreatedAt is the schema descriptor for created_at field.
	flowDescCreatedAt := flowFields[5].Descriptor()
	// flow.DefaultCreatedAt holds the default value on creation for the created_at field.
	flow.DefaultCreatedAt = flowDescCreatedAt.Default.(func() time.Time)
	// flowDescUpdatedAt is the schema descriptor for updated_at field.
	flowDescUpdatedAt := flowFields[6].Descriptor()
	// flow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flow.DefaultUpdatedAt = flowDescUpdatedAt.Default.(func() time.Time)
	// flow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flow.UpdateDefaultUpdatedAt = flowDescUpdatedAt.UpdateDefault.(func() time.Time)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescType is the schema descriptor for type field.
	nodeDescType := nodeFields[0].Descriptor()
	// node.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	node.TypeValidator = nodeDescType.Validators[0].(func(string) error)
	// nodeDescXyflowID is the schema descriptor for xyflow_id field.
	nodeDescXyflowID := nodeFields[1].Descriptor()
	// node.DefaultXyflowID holds the default value on creation for the xyflow_id field.
	node.DefaultXyflowID = nodeDescXyflowID.Default.(string)
	// nodeDescPositionX is the schema descriptor for position_x field.
	nodeDescPositionX := nodeFields[3].Descriptor()
	// node.DefaultPositionX holds the default value on creation for the position_x field.
	node.DefaultPositionX = nodeDescPositionX.Default.(float64)
	// nodeDescPositionY is the schema descriptor for position_y field.
	nodeDescPositionY := nodeFields[4].Descriptor()
	// node.DefaultPositionY holds the default value on creation for the position_y field.
	node.DefaultPositionY = nodeDescPositionY.Default.(float64)
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[5].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	sipserverFields := schema.SIPServer{}.Fields()
	_ = sipserverFields
	// sipserverDescName is the schema descriptor for name field.
	sipserverDescName := sipserverFields[0].Descriptor()
	// sipserver.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sipserver.NameValidator = sipserverDescName.Validators[0].(func(string) error)
	// sipserverDescAddress is the schema descriptor for address field.
	sipserverDescAddress := sipserverFields[1].Descriptor()
	// sipserver.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	sipserver.AddressValidator = sipserverDescAddress.Validators[0].(func(string) error)
	// sipserverDescPort is the schema descriptor for port field.
	sipserverDescPort := sipserverFields[2].Descriptor()
	// sipserver.DefaultPort holds the default value on creation for the port field.
	sipserver.DefaultPort = sipserverDescPort.Default.(int)
	// sipserverDescTransport is the schema descriptor for transport field.
	sipserverDescTransport := sipserverFields[3].Descriptor()
	// sipserver.DefaultTransport holds the default value on creation for the transport field.
	sipserver.DefaultTransport = sipserverDescTransport.Default.(string)
	// sipserverDescUsername is the schema descriptor for username field.
	sipserverDescUsername := sipserverFields[4].Descriptor()
	// sipserver.DefaultUsername holds the default value on creation for the username field.
	sipserver.DefaultUsername = sipserverDescUsername.Default.(string)
	// sipserverDescPassword is the schema descriptor for password field.
	sipserverDescPassword := sipserverFields[5].Descriptor()
	// sipserver.DefaultPassword holds the default value on creation for the password field.
	sipserver.DefaultPassword = sipserverDescPassword.Default.(string)
	// sipserverDescCreatedAt is the schema descriptor for created_at field.
	sipserverDescCreatedAt := sipserverFields[6].Descriptor()
	// sipserver.DefaultCreatedAt holds the default value on creation for the created_at field.
	sipserver.DefaultCreatedAt = sipserverDescCreatedAt.Default.(func() time.Time)
	// sipserverDescUpdatedAt is the schema descriptor for updated_at field.
	sipserverDescUpdatedAt := sipserverFields[7].Descriptor()
	// sipserver.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sipserver.DefaultUpdatedAt = sipserverDescUpdatedAt.Default.(func() time.Time)
	// sipserver.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sipserver.UpdateDefaultUpdatedAt = sipserverDescUpdatedAt.UpdateDefault.(func() time.Time)
}
