// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sipflow/ent/sipserver"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SIPServerCreate is the builder for creating a SIPServer entity.
type SIPServerCreate struct {
	config
	mutation *SIPServerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SIPServerCreate) SetName(v string) *SIPServerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *SIPServerCreate) SetAddress(v string) *SIPServerCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetPort sets the "port" field.
func (_c *SIPServerCreate) SetPort(v int) *SIPServerCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_c *SIPServerCreate) SetNillablePort(v *int) *SIPServerCreate {
	if v != nil {
		_c.SetPort(*v)
	}
	return _c
}

// SetTransport sets the "transport" field.
func (_c *SIPServerCreate) SetTransport(v string) *SIPServerCreate {
	_c.mutation.SetTransport(v)
	return _c
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_c *SIPServerCreate) SetNillableTransport(v *string) *SIPServerCreate {
	if v != nil {
		_c.SetTransport(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *SIPServerCreate) SetUsername(v string) *SIPServerCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *SIPServerCreate) SetNillableUsername(v *string) *SIPServerCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *SIPServerCreate) SetPassword(v string) *SIPServerCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *SIPServerCreate) SetNillablePassword(v *string) *SIPServerCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SIPServerCreate) SetCreatedAt(v time.Time) *SIPServerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SIPServerCreate) SetNillableCreatedAt(v *time.Time) *SIPServerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SIPServerCreate) SetUpdatedAt(v time.Time) *SIPServerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SIPServerCreate) SetNillableUpdatedAt(v *time.Time) *SIPServerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SIPServerMutation object of the builder.
func (_c *SIPServerCreate) Mutation() *SIPServerMutation {
	return _c.mutation
}

// Save creates the SIPServer in the database.
func (_c *SIPServerCreate) Save(ctx context.Context) (*SIPServer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SIPServerCreate) SaveX(ctx context.Context) *SIPServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SIPServerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SIPServerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SIPServerCreate) defaults() {
	if _, ok := _c.mutation.Port(); !ok {
		v := sipserver.DefaultPort
		_c.mutation.SetPort(v)
	}
	if _, ok := _c.mutation.Transport(); !ok {
		v := sipserver.DefaultTransport
		_c.mutation.SetTransport(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := sipserver.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.Password(); !ok {
		v := sipserver.DefaultPassword
		_c.mutation.SetPassword(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sipserver.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sipserver.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SIPServerCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SIPServer.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sipserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SIPServer.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "SIPServer.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := sipserver.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "SIPServer.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "SIPServer.port"`)}
	}
	if _, ok := _c.mutation.Transport(); !ok {
		return &ValidationError{Name: "transport", err: errors.New(`ent: missing required field "SIPServer.transport"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SIPServer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SIPServer.updated_at"`)}
	}
	return nil
}

func (_c *SIPServerCreate) sqlSave(ctx context.Context) (*SIPServer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SIPServerCreate) createSpec() (*SIPServer, *sqlgraph.CreateSpec) {
	var (
		_node = &SIPServer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sipserver.Table, sqlgraph.NewFieldSpec(sipserver.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sipserver.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(sipserver.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(sipserver.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.Transport(); ok {
		_spec.SetField(sipserver.FieldTransport, field.TypeString, value)
		_node.Transport = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(sipserver.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(sipserver.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sipserver.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sipserver.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SIPServerCreateBulk is the builder for creating many SIPServer entities in bulk.
type SIPServerCreateBulk struct {
	config
	err      error
	builders []*SIPServerCreate
}

// Save creates the SIPServer entities in the database.
func (_c *SIPServerCreateBulk) Save(ctx context.Context) ([]*SIPServer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SIPServer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SIPServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SIPServerCreateBulk) SaveX(ctx context.Context) []*SIPServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SIPServerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SIPServerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
