// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sipflow/ent/predicate"
	"sipflow/ent/sipserver"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SIPServerDelete is the builder for deleting a SIPServer entity.
type SIPServerDelete struct {
	config
	hooks    []Hook
	mutation *SIPServerMutation
}

// Where appends a list predicates to the SIPServerDelete builder.
func (_d *SIPServerDelete) Where(ps ...predicate.SIPServer) *SIPServerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SIPServerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SIPServerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SIPServerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sipserver.Table, sqlgraph.NewFieldSpec(sipserver.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SIPServerDeleteOne is the builder for deleting a single SIPServer entity.
type SIPServerDeleteOne struct {
	_d *SIPServerDelete
}

// Where appends a list predicates to the SIPServerDelete builder.
func (_d *SIPServerDeleteOne) Where(ps ...predicate.SIPServer) *SIPServerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SIPServerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sipserver.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SIPServerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
