// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sipflow/ent/predicate"
	"sipflow/ent/sipserver"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SIPServerUpdate is the builder for updating SIPServer entities.
type SIPServerUpdate struct {
	config
	hooks    []Hook
	mutation *SIPServerMutation
}

// Where appends a list predicates to the SIPServerUpdate builder.
func (_u *SIPServerUpdate) Where(ps ...predicate.SIPServer) *SIPServerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SIPServerUpdate) SetName(v string) *SIPServerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SIPServerUpdate) SetNillableName(v *string) *SIPServerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *SIPServerUpdate) SetAddress(v string) *SIPServerUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *SIPServerUpdate) SetNillableAddress(v *string) *SIPServerUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *SIPServerUpdate) SetPort(v int) *SIPServerUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *SIPServerUpdate) SetNillablePort(v *int) *SIPServerUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *SIPServerUpdate) AddPort(v int) *SIPServerUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetTransport sets the "transport" field.
func (_u *SIPServerUpdate) SetTransport(v string) *SIPServerUpdate {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *SIPServerUpdate) SetNillableTransport(v *string) *SIPServerUpdate {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *SIPServerUpdate) SetUsername(v string) *SIPServerUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SIPServerUpdate) SetNillableUsername(v *string) *SIPServerUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *SIPServerUpdate) ClearUsername() *SIPServerUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *SIPServerUpdate) SetPassword(v string) *SIPServerUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *SIPServerUpdate) SetNillablePassword(v *string) *SIPServerUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *SIPServerUpdate) ClearPassword() *SIPServerUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SIPServerUpdate) SetUpdatedAt(v time.Time) *SIPServerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SIPServerMutation object of the builder.
func (_u *SIPServerUpdate) Mutation() *SIPServerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SIPServerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SIPServerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SIPServerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SIPServerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SIPServerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sipserver.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SIPServerUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sipserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SIPServer.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := sipserver.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "SIPServer.address": %w`, err)}
		}
	}
	return nil
}

func (_u *SIPServerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sipserver.Table, sipserver.Columns, sqlgraph.NewFieldSpec(sipserver.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sipserver.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(sipserver.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(sipserver.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(sipserver.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(sipserver.FieldTransport, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(sipserver.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(sipserver.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(sipserver.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(sipserver.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sipserver.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sipserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SIPServerUpdateOne is the builder for updating a single SIPServer entity.
type SIPServerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SIPServerMutation
}

// SetName sets the "name" field.
func (_u *SIPServerUpdateOne) SetName(v string) *SIPServerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SIPServerUpdateOne) SetNillableName(v *string) *SIPServerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *SIPServerUpdateOne) SetAddress(v string) *SIPServerUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *SIPServerUpdateOne) SetNillableAddress(v *string) *SIPServerUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *SIPServerUpdateOne) SetPort(v int) *SIPServerUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *SIPServerUpdateOne) SetNillablePort(v *int) *SIPServerUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *SIPServerUpdateOne) AddPort(v int) *SIPServerUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetTransport sets the "transport" field.
func (_u *SIPServerUpdateOne) SetTransport(v string) *SIPServerUpdateOne {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *SIPServerUpdateOne) SetNillableTransport(v *string) *SIPServerUpdateOne {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *SIPServerUpdateOne) SetUsername(v string) *SIPServerUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SIPServerUpdateOne) SetNillableUsername(v *string) *SIPServerUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *SIPServerUpdateOne) ClearUsername() *SIPServerUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *SIPServerUpdateOne) SetPassword(v string) *SIPServerUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *SIPServerUpdateOne) SetNillablePassword(v *string) *SIPServerUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *SIPServerUpdateOne) ClearPassword() *SIPServerUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SIPServerUpdateOne) SetUpdatedAt(v time.Time) *SIPServerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SIPServerMutation object of the builder.
func (_u *SIPServerUpdateOne) Mutation() *SIPServerMutation {
	return _u.mutation
}

// Where appends a list predicates to the SIPServerUpdate builder.
func (_u *SIPServerUpdateOne) Where(ps ...predicate.SIPServer) *SIPServerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SIPServerUpdateOne) Select(field string, fields ...string) *SIPServerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SIPServer entity.
func (_u *SIPServerUpdateOne) Save(ctx context.Context) (*SIPServer, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SIPServerUpdateOne) SaveX(ctx context.Context) *SIPServer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SIPServerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SIPServerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SIPServerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sipserver.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SIPServerUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sipserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SIPServer.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := sipserver.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "SIPServer.address": %w`, err)}
		}
	}
	return nil
}

func (_u *SIPServerUpdateOne) sqlSave(ctx context.Context) (_node *SIPServer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sipserver.Table, sipserver.Columns, sqlgraph.NewFieldSpec(sipserver.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SIPServer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sipserver.FieldID)
		for _, f := range fields {
			if !sipserver.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sipserver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sipserver.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(sipserver.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(sipserver.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(sipserver.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(sipserver.FieldTransport, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(sipserver.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(sipserver.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(sipserver.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(sipserver.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sipserver.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SIPServer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sipserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
