/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as FlowIndexRouteImport } from './routes/flow.index'
import { Route as SettingsPbxRouteImport } from './routes/settings.pbx'
import { Route as SettingsMediaRouteImport } from './routes/settings.media'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as FlowScenarioRouteImport } from './routes/flow.scenario'
import { Route as FlowPaletteRouteImport } from './routes/flow.palette'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const FlowIndexRoute = FlowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlowRoute,
} as any)
const SettingsPbxRoute = SettingsPbxRouteImport.update({
  id: '/pbx',
  path: '/pbx',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMediaRoute = SettingsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const FlowScenarioRoute = FlowScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => FlowRoute,
} as any)
const FlowPaletteRoute = FlowPaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => FlowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flow': typeof FlowRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/flow/palette': typeof FlowPaletteRoute
  '/flow/scenario': typeof FlowScenarioRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/media': typeof SettingsMediaRoute
  '/settings/pbx': typeof SettingsPbxRoute
  '/flow/': typeof FlowIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flow/palette': typeof FlowPaletteRoute
  '/flow/scenario': typeof FlowScenarioRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/media': typeof SettingsMediaRoute
  '/settings/pbx': typeof SettingsPbxRoute
  '/flow': typeof FlowIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flow': typeof FlowRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/flow/palette': typeof FlowPaletteRoute
  '/flow/scenario': typeof FlowScenarioRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/media': typeof SettingsMediaRoute
  '/settings/pbx': typeof SettingsPbxRoute
  '/flow/': typeof FlowIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flow'
    | '/settings'
    | '/flow/palette'
    | '/flow/scenario'
    | '/settings/general'
    | '/settings/media'
    | '/settings/pbx'
    | '/flow/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flow/palette'
    | '/flow/scenario'
    | '/settings/general'
    | '/settings/media'
    | '/settings/pbx'
    | '/flow'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/flow'
    | '/settings'
    | '/flow/palette'
    | '/flow/scenario'
    | '/settings/general'
    | '/settings/media'
    | '/settings/pbx'
    | '/flow/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowRoute: typeof FlowRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/flow/': {
      id: '/flow/'
      path: '/'
      fullPath: '/flow/'
      preLoaderRoute: typeof FlowIndexRouteImport
      parentRoute: typeof FlowRoute
    }
    '/settings/pbx': {
      id: '/settings/pbx'
      path: '/pbx'
      fullPath: '/settings/pbx'
      preLoaderRoute: typeof SettingsPbxRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/media': {
      id: '/settings/media'
      path: '/media'
      fullPath: '/settings/media'
      preLoaderRoute: typeof SettingsMediaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/flow/scenario': {
      id: '/flow/scenario'
      path: '/scenario'
      fullPath: '/flow/scenario'
      preLoaderRoute: typeof FlowScenarioRouteImport
      parentRoute: typeof FlowRoute
    }
    '/flow/palette': {
      id: '/flow/palette'
      path: '/palette'
      fullPath: '/flow/palette'
      preLoaderRoute: typeof FlowPaletteRouteImport
      parentRoute: typeof FlowRoute
    }
  }
}

interface FlowRouteChildren {
  FlowPaletteRoute: typeof FlowPaletteRoute
  FlowScenarioRoute: typeof FlowScenarioRoute
  FlowIndexRoute: typeof FlowIndexRoute
}

const FlowRouteChildren: FlowRouteChildren = {
  FlowPaletteRoute: FlowPaletteRoute,
  FlowScenarioRoute: FlowScenarioRoute,
  FlowIndexRoute: FlowIndexRoute,
}

const FlowRouteWithChildren = FlowRoute._addFileChildren(FlowRouteChildren)

interface SettingsRouteChildren {
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsMediaRoute: typeof SettingsMediaRoute
  SettingsPbxRoute: typeof SettingsPbxRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsMediaRoute: SettingsMediaRoute,
  SettingsPbxRoute: SettingsPbxRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowRoute: FlowRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
