// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetVersion():Promise<string>;

export function Ping():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
