// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetSupportedCommands():Promise<Array<string>>;

export function GetSupportedEvents():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function IsRunning():Promise<boolean>;

export function Ping():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartScenario(arg1:string):Promise<void>;

export function StopScenario():Promise<void>;
