// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {binding} from '../models';

export function SelectWAVFile():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ValidateWAVFile(arg1:string):Promise<binding.WAVValidationResult>;
