// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectWAVFile() {
  return window['go']['binding']['MediaBinding']['SelectWAVFile']();
}

export function SetContext(arg1) {
  return window['go']['binding']['MediaBinding']['SetContext'](arg1);
}

export function ValidateWAVFile(arg1) {
  return window['go']['binding']['MediaBinding']['ValidateWAVFile'](arg1);
}
