// Temporary stub for ScenarioBinding - will be regenerated by Wails
// @ts-check

export function CreateScenario(name) {
  return window['go']['binding']['ScenarioBinding']['CreateScenario'](name);
}

export function SaveScenario(id, flowData) {
  return window['go']['binding']['ScenarioBinding']['SaveScenario'](id, flowData);
}

export function LoadScenario(id) {
  return window['go']['binding']['ScenarioBinding']['LoadScenario'](id);
}

export function ListScenarios() {
  return window['go']['binding']['ScenarioBinding']['ListScenarios']();
}

export function DeleteScenario(id) {
  return window['go']['binding']['ScenarioBinding']['DeleteScenario'](id);
}

export function RenameScenario(id, newName) {
  return window['go']['binding']['ScenarioBinding']['RenameScenario'](id, newName);
}
