// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScenario(arg1) {
  return window['go']['binding']['ScenarioBinding']['CreateScenario'](arg1);
}

export function DeleteScenario(arg1) {
  return window['go']['binding']['ScenarioBinding']['DeleteScenario'](arg1);
}

export function ListScenarios() {
  return window['go']['binding']['ScenarioBinding']['ListScenarios']();
}

export function LoadScenario(arg1) {
  return window['go']['binding']['ScenarioBinding']['LoadScenario'](arg1);
}

export function RenameScenario(arg1, arg2) {
  return window['go']['binding']['ScenarioBinding']['RenameScenario'](arg1, arg2);
}

export function SaveScenario(arg1, arg2) {
  return window['go']['binding']['ScenarioBinding']['SaveScenario'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['binding']['ScenarioBinding']['SetContext'](arg1);
}
