// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';
import {dto} from '../models';

export function CreateScenario(arg1:string):Promise<entity.Scenario>;

export function DeleteScenario(arg1:string):Promise<void>;

export function DeleteScenarioEdge(arg1:string,arg2:string):Promise<void>;

export function DeleteScenarioEdgesByScenario(arg1:string):Promise<void>;

export function DeleteScenarioNode(arg1:string,arg2:string):Promise<void>;

export function DeleteScenarioNodesByScenario(arg1:string):Promise<void>;

export function ListScenarioEdges(arg1:string):Promise<Array<entity.EdgeRecord>>;

export function ListScenarioNodes(arg1:string):Promise<Array<entity.NodeRecord>>;

export function ListScenarios():Promise<Array<entity.ScenarioListItem>>;

export function LoadNodeProperty(arg1:string,arg2:string):Promise<entity.NodePropertyRecord>;

export function LoadScenario(arg1:string):Promise<entity.Scenario>;

export function RenameScenario(arg1:string,arg2:string):Promise<void>;

export function SaveScenario(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpsertNodeProperty(arg1:dto.NodePropertyUpsert):Promise<void>;

export function UpsertScenarioEdge(arg1:dto.EdgeUpsert):Promise<void>;

export function UpsertScenarioNode(arg1:dto.NodeUpsert):Promise<void>;
