// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding} from '../models';
import {context} from '../models';

export function CreateScenario(arg1:string):Promise<binding.ScenarioDTO>;

export function DeleteScenario(arg1:string):Promise<void>;

export function ListScenarios():Promise<Array<binding.ScenarioListItemDTO>>;

export function LoadScenario(arg1:string):Promise<binding.ScenarioDTO>;

export function RenameScenario(arg1:string,arg2:string):Promise<void>;

export function SaveScenario(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
