// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Edge is the predicate function for edge builders.
type Edge func(*sql.Selector)

// Flow is the predicate function for flow builders.
type Flow func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)
